### ISSUE TITLE
Points,hours,ranks transfer

### ISSUE THREAD

**Issue by itsjusttriz** [PhantomBot/PhantomBot#1504]
PhantomBot Version:
O/S Version:
Java Version:
Web Browser Version (if Panel related):

Detailed Description:
Usually when my friend updates her bot, she keeps the phantombot.db file. Is there a way of keeping the points, ranks and hours WITHOUT saving the custom commands? She wants to reset All her commands but keep the points etc

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by kojitsari** [comment]
She'd need to use an sqlite data base editor to delete the table that contains the custom commands
Such as: http://sqlitebrowser.org/
