### ISSUE TITLE
Raffle System

### ISSUE THREAD

**Issue by Shockwave2k** [PhantomBot/PhantomBot#159]
The Raffle System seems to be broken atm.
You can open a raffle but no one seems to be able to enter the raffle same for ticket raffle.
For the normal raffle it also wont autoclose (after time was added to the raffle) but im not sure if an entry is needed for this.

**Comment by phantomindex** [comment]
You're using 2.0.5?

**Comment by Shockwave2k** [comment]
yes

**Comment by ghost** [comment]
By default both raffle systems have the enter message toggled off. And I just pushed a fix for the timer issues.
