### ISSUE TITLE
[Question]Can multiple PhantomBots share a DB?

### ISSUE THREAD

**Issue by Griefed** [PhantomBot/PhantomBot#2345]
Heya everyone,

I'd like to know whether multiple PhantomBots can share one DB.
I'd like to set up one master who can add commands, keywords etc. so other bots can access it's database in order to all have the same commands etc. available.
Since one PB can only moderate one twitch channel, I need to work that limitation somehow.

The idea is to have a Twitch-Team-Bot, which all members of said team can use, with a set of commands created to suite the needs of said team, like promoting each other, social links etc. Obviously I would still need to create slaves for each streamer, but I wouldn't need to add all commands and keywords etc. again and again for each individual bot.

Has anyone tried something like that yet and is willing to share their insights? Or can someone tell me wheter what I would like to do is even possible?

Thank you for your time.
Cheers,
Griefed

**Comment by gmt2001** [comment]
You could do this with MySQL, but it requires very specialized setup.

You would need a separate schema for each channel and a schema for the shared commands and keywords tables.

Then on each channels schema, you would need a renamed commands and keywords table.

Then on each channels schema, you would need to create a view using the normal name of the commands and keywords table which is defined as a SELECT on both the renamed commands or keywords table, and the one from the shared schema.

You would also need a trigger on INSERT, UPDATE, DELETE for each view to redirect those statements to the renames commands or keywords table of the channel.

NOTE: PhantomBot is not actually designed for this and it has never been tried before.

**Comment by Griefed** [comment]
Thank you for your feedback, it's very much appreciated. That's a lot of work and with my current knowledge of databases no very likely to happen anytime soon.

Thank you very much. 👍

**Comment by taradinoc** [comment]
Without fancy SQL tricks, you could also do this by modifying the command/keyword modules to make the bots whisper commands to keep each other in sync.
