### ISSUE TITLE
(touser) & (pointtouser) wont use given variables if used in command

### ISSUE THREAD

**Issue by CapraGenus** [PhantomBot/PhantomBot#2346]
PhantomBot Version: 3.3.0 (stable) (Revision: 44873ee)
Operating System: Linux
Java Version: 11.0.4+10-LTS

Detailed Description: When using the variables (touser) or (pointtouser) in a command they always refer to the user giving the command and not the variable itself.

Steps to Reproduce: create a custom command such as 

Go check out (touser) on their twitch channel at twitch.tv/(touser) this streamer is cool

Run the command !so testuser

The output will show the custom command but with the variables replaced as the name of the user running the command and not the variable given.

Screenshots (if applicable):
https://imgur.com/a/REqyk2D

**Comment by gmt2001** [comment]
`(touser)` is fixed in #2344 

Both can currently be used by doing `(touser (1))` or `(pointtouser (1))`

I will restore the correct behavior for `(pointtouser)` in another commit to #2344 shortly
