### ISSUE TITLE
Notice interval command accepts no interval

### ISSUE THREAD

**Issue by Runesmacher** [PhantomBot/PhantomBot#2352]
PhantomBot Version:
O/S Version: Ubuntu 18.04.1 LTS
Java Version: 1.8.0_265

Detailed Description:
the !notice interval command accepts no parameters and sets the actual notice time to an empty value

Steps to Reproduce:
Enable the Timer module
Type !notice interval in chat with no number

Logs:
No applicable logs found, chat logs can be seen in the screenshot below

Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/979451/90984157-9c082280-e573-11ea-864a-01795fcb3a9c.png)

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/PhantomBot/blob/9115d8b8f406d0db511426f76e447f524c22acd7/javascript-source/systems/noticeSystem.js#L275
