### ISSUE TITLE
custom commands with readfilerand sounds aren't working anymore

### ISSUE THREAD

**Issue by himpich** [PhantomBot/PhantomBot#2372]
PhantomBot Version: 3.3.1
O/S Version: linux, ubuntu xenial
Java Version: packaged version
Web Browser Version (if Panel related): not related

Detailed Description:
We have several custom commands using the readfilerand command to get a random soundcommand from a textfile.
Since the update the bot shows the random line from the textfile but this does not trigger the sound anymore
We use this to play random sounds for several commands.

Before the update (from 3.2.3) everything worked.

I guess this is related to https://github.com/PhantomBot/PhantomBot/pull/2253 but I could not find how to fix my problem.

Steps to Reproduce:
create a textfile, e.g. addons/speichern.txt - contents:
```
(playsound speichern_julia)
(playsound speichern_skexis)
(playsound speichern_fuxx)
```
Add a custom command containing readfilerand(speichern.txt)

trigger the command. The output will be a line (including the brackets) from the textfile, but this isn't parsed anymore.

Logs:
no errors in the logfiles

**Comment by gmt2001** [comment]
Already fixed

`(readfilerand)` must now be wrapped in `(unescape)` to allow it to return new commands. This is a security feature that prevents user input from running an unintentional command
Usage: `(unescape (readfilerand test.txt))`

Update to nightly or wait for 3.3.2 to fix a bug preventing audio hooks from working at all

**Comment by himpich** [comment]
Thanks! That wasn't clear for me.
