### ISSUE TITLE
Embed chat dont work

### ISSUE THREAD

**Issue by C74K** [PhantomBot/PhantomBot#2376]
PhantomBot Version:

 **PhantomBot Version: 3.3.2-NB-20200906 (nightly_build)**

O/S Version: 

Ubuntu 14.04.6 LTS (GNU/Linux 4.4.0-142-generic i686)

Java Version:

penjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-2ubuntu114.04)
OpenJDK Server VM (build 11.0.5+10-post-Ubuntu-2ubuntu114.04, mixed mode, sharin   

Web Browser Version (if Panel related):

85.0.4183.83 (Oficjalna wersja) (64-bitowa)

Detailed Description:
inside Dashboard Panels dont work

Steps to Reproduce:
-

Logs:
-

Screenshots (if applicable):

![pobrane](https://user-images.githubusercontent.com/3368595/92330711-579b7d00-f071-11ea-8278-198d67643f56.png)

**Comment by gmt2001** [comment]
https://phantom.bot/guides/#guide=content/integrations/twitchembeds

**Comment by C74K** [comment]
method 1 dont work webpanel dont load

**Comment by gmt2001** [comment]
Domain name required for method 1

**Comment by C74K** [comment]
THX Works. 

nothing about this in manual on webpage.

**Comment by gmt2001** [comment]
Updated the guide 👍
