### ISSUE TITLE
Twitch API v5 deprecated

### ISSUE THREAD

**Issue by AevumDecessus** [PhantomBot/PhantomBot#2385]
According to the [API Docs](https://dev.twitch.tv/docs/v5), they've now deprecated the v5 kraken api in favor of the new helix api endpoint.

No timeline has been provided for shutdown of the kraken api, but it would be a good idea to start converting the api over to the helix one. Originally the deprecation of v5 was supposed to be this year, but no updates have been provided in a while.

Helix oauth requires the client_id sent in the headers to match the one used to request the oauth token in the first place, which would mean hardcoding the one used for the [Oauth Generator](https://phantom.bot/oauth/)

More Info:
* [Requiring OAuth for Helix Twitch API Endpoints](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916)
* [Twitch Authentication: Understanding Which Protocol and Flow is Right For You](https://blog.twitch.tv/en/2019/11/06/twitch-authentication-understanding-which-protocol-and-flow-is-right-for-you/)
* [Twitch API v3 and v5 Deprecation Updates](https://discuss.dev.twitch.tv/t/twitch-api-v3-and-v5-deprecation-updates/19144)

**Comment by BrandenB** [comment]
Hello,

Version 5 of Twitch's API was deprecated the day it was released. Twitch has been trying to get people to move over to their new Helix API, but as it sits right now it's far from complete. The new API is missing a bunch of features that are needed for PhantomBot to work. Helix is also not reliable last I've checked and as of right now is not worth the hassle to convert over.

Twitch has also been making a lot of changes to Helix, so it could break at any time and make PhantomBot even less stable.
