### ISSUE TITLE
I will no longer be using PhantomBot

### ISSUE THREAD

**Issue by qome** [PhantomBot/PhantomBot#2405]
I was IP banned from your Discord today by the user who blanked out his nickname so people wouldn't know who he was.

I asked the individual to test something that I found broken and he lied to me and told me he already had. When I called him out he called me a child and IP banned me.

I will no longer be using PhantomBot since apparently your team is unwilling to act like sane people.

**Comment by kojitsari** [comment]
This person failed to attempt to build from source, was using the project it a manner it was not intended to be and as a result running into 'bugs.' 

After failing to provide any actual proof of a bug they became hostile and as a were removed from our Discord. They have now been block from this repository also.

**Comment by nadgon** [comment]
my friend be banned to without warning and without reason
