### ISSUE TITLE
Discord Mod and Command Log

### ISSUE THREAD

**Issue by Thaliruth1** [PhantomBot/PhantomBot#2408]
PhantomBot Version:  3.3.5
O/S Version: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related): Chrome

Detailed Description:
Hello, I've been noticing for a while now that no logs seem to be posted in my Discord Channel. When a mod bans a user it does not appear in my Discord Channel anymore. The last entry there is from 04/26/2020

I have now banned and unbanned several users for testing, unfortunately nothing happens in the Log Channel anymore. Can anyone confirm this?

Steps to Reproduce:
Enable Twitch Moderation: YES
Logging Channel : mychannel (written without #)

Restart the bot.
Go to Twitch and ban a user /ban username This is a Test

Look at Discord in your channel, there is nothing there.

Logs:
There are no logs in the Moderation folder

**Comment by kojitsari** [comment]
We haven't had any reports via Discord or Issues that this is occurring on the latest release. Closing this, please open another issue if this is still occurring on the latest release.

**Comment by Thaliruth** [comment]
I am now running the latest version 3.4.1 also here is no log in my Discord channel, or in the directory /logs

I have a user with 

/ban name this is a test
and 
/unban user

Banned and unbanned, but as usual no logging anymore.

**Comment by Thaliruth** [comment]
> We haven't had any reports via Discord or Issues that this is occurring on the latest release. Closing this, please open another issue if this is still occurring on the latest release.

I am now running the latest version 3.4.1 also here is no log in my Discord channel, or in the directory /logs

I have a user with

/ban name this is a test
and
/unban user

Banned and unbanned, but as usual no logging anymore.
