### ISSUE TITLE
Adding custom commands without exclamation mark.

### ISSUE THREAD

**Issue by Alharthi** [PhantomBot/PhantomBot#2411]
PhantomBot Version:
O/S Version:
Java Version:
Web Browser Version (if Panel related):

Detailed Description:
Hello, is it possible to add a command without '!' for example I want to add a custom command like "time?" or in Arabic that ends with a question mark only, how to do that?

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by robsdedude** [comment]
This is currently not possible. Adding this feature would require quite a lot of work.

**Comment by BrandenB** [comment]
You can use keywords

**Comment by Alharthi** [comment]
> You can use keywords

It won't work and function like commands, I can't use "uptime?" for example as a keyword.

**Comment by Alharthi** [comment]
> This is currently not possible. Adding this feature would require quite a lot of work.

I see, sorry to hear that.

**Comment by BrandenB** [comment]
You can use `uptime?` as a keyword and make it trigger a command.

`!keyword add uptime? command:uptime`

**Comment by robsdedude** [comment]
> > This is currently not possible. Adding this feature would require quite a lot of work.
> 
> I see, sorry to hear that.

I didn't think of keywords. :brain: 


> `!keyword add uptime? command:uptime`

This would cause the keyword to mach anywhere. So if someone in chat would say `Does anyone know the uptime?`, the bot would react as well. If you want the bot to only react on `uptime?` and nothing else, you have to use a regular expression like so

`!keyword add --regex ^uptime\?$ command:uptime`

Explanation: `^` makes sure, that this is the beginning of the message, `$` makes sure that the end of the message has been reached. Regexes have some characters that have a special meaning. You don't have to bother what that meaning is, you just need to know that you have to put a `\` in front of them to tell the regex "this has no special meaning, just take it for what it is". Those symbols include: `.*+?^${}()|[]\`. So for example, if you have a `(` in your keyowrd, replace it with `\(` and you are good to go.

I think this issue can be closed?

**Comment by Alharthi** [comment]
Thank you, That worked fine!
