### ISSUE TITLE
Feature Request: Mod activity stats

### ISSUE THREAD

**Issue by TheBlackHawk1337** [PhantomBot/PhantomBot#2420]
Detailed Description:

My idea is to see the activity of my mods.
Stuff like detailed stats about chat time, chat messages, timeouts, command uses etc.

thanks

**Comment by dungi** [comment]
I guess this is not a feature, everyone needs, cause I don't want to track how long my mods are in chat and what they are writing. This should be a custom script, only for for custom purposes. Timeouts can allready bin logged. 

But maybe this is something 99% of the user needs... but I will not set my mods under this pressure.

**Comment by kojitsari** [comment]
This is something suited for a custom module.
