### ISSUE TITLE
Phantom don't react from autohost events 

### ISSUE THREAD

**Issue by GeekTale** [PhantomBot/PhantomBot#2425]
The bot react to normal host events but I don't see any autohost event reaction and it has an implementation in the code.

**Comment by ryantechdev** [comment]
![image](https://user-images.githubusercontent.com/66895770/101694504-30be5f80-3a41-11eb-85f0-645b675559cf.png)

**Comment by GeekTale** [comment]
I have activated this option...

![Screenshot_20201210-002745_AnyDesk~2.jpg](https://user-images.githubusercontent.com/29758691/101701152-9d0b8400-3a7e-11eb-8e20-d1dad19aee4b.jpg)

**Comment by gmt2001** [comment]
Looking at Twitch's documentation, it appears they may not be sending specifically marked events for this anymore
