### ISSUE TITLE
Add Users to queue from external

### ISSUE THREAD

**Issue by mkshb** [PhantomBot/PhantomBot#2427]
PhantomBot Version: 3.3.5
O/S Version: Linux / Docker
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):

Detailed Description: 
Is it possible to add user to the queue from an external application?
Database table has 3 fields 
section = ???
variable = Twitch username
value = JSON with some infos

If i add a row there its shown in panel but never get drawn.

Thanks in advance!

**Comment by kojitsari** [comment]
You would be better making a custom variant of the queue system module. The odds are you're not updating the variable that handles the number of keys in the list of entrants.
