### ISSUE TITLE
Feature-Request: Play audiohook with channelpoints

### ISSUE THREAD

**Issue by TheBlackHawk1337** [PhantomBot/PhantomBot#2436]
Detailed Description: Hello, it would be nice when you could add the option to play audiohooks with the channel points handler

**Comment by FlikstRR** [comment]
I'm looking to do exactly this right now. Would be amazing to know if any others are either looking to develop the same thing or are looking for the feature.

**Comment by dungi** [comment]
You know you can already do this with the newest version?

**Comment by Casper-O** [comment]
@dungi could you tell how?

as far i seen, i could only use the bot own points?

**Comment by kojitsari** [comment]
You'll have to edit the code, there's a guide on the function you need https://phantombot.github.io/PhantomBot/guides/#guide=content/moduleguides/channelpoints. As of now there is zero plan to use channel points in default scripts.
