### ISSUE TITLE
"Successfully sent a message as the bot!" but no Message in Chat

### ISSUE THREAD

**Issue by SethFalco** [PhantomBot/PhantomBot#2444]
PhantomBot Version: 3.4.1 (stable) (Revision: 6d1a942)
Operating System: Linux
Java Version: 11.0.4+10-LTS

Detailed Description:
While setting up the bot for the first time, the bot was unable to respond to commands or send messages.

I'm not 100% sure what the solution to this was, but I decided to login to the bot account manually and visit the casters channel, then accepts the rules. Following this the bot could immediately respond to custom commands and send messages manually from the dashboard.

However, while the bot was in the state that it couldn't send a message, it was difficult to detect the problem, and the web dashboard were showing a notification that the messages were sent _successfully_.

The dashboard, however, should not be saying these messages were successful if they weren't.

Logs:
At `[02-03-2021 @ 13:47:22.442 GMT]` we made the bot a moderator, before and after this the success message depicted by the screenshot is what the dashboard displayed when trying to send a message as the bot, despite receiving no message in chat.

The issue continued until `[02-03-2021 @ 14:09:07.083 GMT]`, this is when I logged into the account manually to accept rules which appears to have resolved the issue.

https://gist.github.com/SethFalco/873d261d100adce47bf67589a2898813

Screenshots (if applicable):

![image](https://user-images.githubusercontent.com/22801583/106761053-bbcc6800-6634-11eb-8125-05e03ea34b0e.png)  
> The dashboard displaying a success message, despite no message being sent in chat.

**Comment by gmt2001** [comment]
After testing this out, issue appears to be that the bot wasn't moderator at the time of bootup.

The fact that it worked after you accepted the rules was just good timing, as the bot had performed another mod-check between the time you added it as a moderator and the time you accepted the channel rules.

The bot does not initialize the scripts until the mod-check passes

**Comment by SethFalco** [comment]
Sorry, but just want to check should this have been closed?

The main issue this was reporting was that the dashboard was saying the message was sent successfully, despite the message not being sent successfully.

The rest was just context around what I was doing at the time, sorry if it made the issue unclear.

**Comment by Tomvapor** [comment]
Same issue here.
I use a cmd in Stream Chat, Console responsed but no Bot message in Stream Chat.
