### ISSUE TITLE
YouTube Embed issue for song requests feature

### ISSUE THREAD

**Issue by Exavior** [PhantomBot/PhantomBot#2460]
PhantomBot Version:  3.4.2 (stable) (Revision: bf69ab8) and one older version
O/S Version:  Windows 10
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):   Google Chrome - Version 88.0.4324.190 (Official Build) (64-bit)

Detailed Description:
No matter what YouTube video is provided the bot and error log always responds with " YoutubeVideo::exception: This video is not allowed to be embedded" even for videos I own and allow embedding for, even for videos that predate YouTube adding the embedding metadata flag.  I've tried 80+ YouTube links so far with no luck.

Clicking the "play" icon in the YTP default playlist UI also does not play anything or return errors.  This is for the 4 default songs that are part of the default playlist after the reset command has been issued.   Example, index 0 "whatfunk - Waves FREE CC0 NO COPYRIGHT Royalty Free Music"  

I even tried taking the same "whatfunk" track from the default playlist and manually adding it and get the following:
 Failed adding song to queue: YouTube error (This video is not allowed to be embedded (ID: vY_kyk8yL9U))

Chrome console for YTP shows no JS errors or anything to be concerned about.

Also worth noting, every time I close the YTP tab the bot respons with the "song requests have been disabled" message exactly 19 times in a row, without fail. 

I disabled adblockers etc to rule out a plugin contributing to the issue.

Steps to Reproduce:
Open song requests
Request a song

Logs:

Sample, just picture the same message 80+ times with different IDs

[03-11-2021 @ 12:17:17.009 PST] [youtubePlayer.js:743] YoutubeVideo::exception: This video is not allowed to be embedded (ID: vY_kyk8yL9U)

Screenshots (if applicable):

**Comment by Exavior** [comment]
I've updated my YouTube credentials and still have this issue.  No videos show as embedable and closing the YouToube player window results in 19 "song requests have been disabled" messages.  Any ideas what else I can try to resolve this?

Nothing much new in error logs, same false "not allowed to be embedded" error on videos that can be embedded

[03-18-2021 @ 12:12:40.621 PDT] [youtubePlayer.js:743] YoutubeVideo::exception: This video is not allowed to be embedded (ID: 9Y5CCHacHfk)

An old log does show the following (before new key was generated)

[03-11-2021 @ 21:17:44.590 GMT] [GetData()@YouTubeAPIv3.java:134] YouTubeAPIv3 Error: [Domain] youtube.quota [Reason] quotaExceeded 

Odd that a quota would be exceeded for a feature that is not being used at all.  What else would be connecting to the YouTube API?  I never have the YTP tab open since it's not working, and nothing else on the bot should be using it.

**Comment by arcreigh** [comment]
Having the same problem here, PhantomBot was one of the few bots that had a functional song request feature. I wonder if youtube themselves have done something to prohibit this kind of behavior.
