### ISSUE TITLE
Ubuntu guide is incomplete

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2466]
PhantomBot Version: Any
O/S Version: Ubuntu Any (in this case 20.04)

I'm in the process of setting up a dedicated VM for my Phantom Bot setup, and I noticed in the setup instructions that it didn't show a method to allow the dedicated user to use any ports below 1024 (443, in this case), which is something that needs elevated privileges.

"ERROR] [checkPortAvailabity()@PhantomBot.java:305] Port is already in use: 443"

I know for a fact this port isn't in use, and it works when I run sudo for it. However, running the app as sudo means that any created files are likely going to be owned by root, not the dedicated bot user.

Not sure this moment what the best method is to address this, but the documentation is lacking in this area, and might want to also update it from 16.04 to maybe 20.04? Not sure if much really needs to change otherwise though.

**Comment by BloodyIron** [comment]
Yeah it's looking like only root should be able to bind to ports 1024 and lower, and enabling other users to do so presents a tangible security risk (from multiple sources speaking on the topic). So I'm thinking the Centos guide also needs to be adjusted to reflect this.

**Comment by BloodyIron** [comment]
Okay so I see the guide talks about default port of 25000, but I had to switch to 443 for one of the components to work (forget which one this moment), and it's probably a good idea for the guides to be adapted to just use 443 by default anyways.

**Comment by gmt2001** [comment]
The information about this is included in the guide for enabling the Twitch Embeds, which is the sole reason currently for switching to 443. The wording will be improved a little bit in an upcoming commit.
