### ISSUE TITLE
[Feature Request] Changing order of things (Timers, etc)

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2468]
PhantomBot Version: 3.4.2
O/S Version: Ubuntu 20.04
 
Hey, any chance we can get the ability to change the order of Timers and other aspects? I'd like to tune better which things come before others, but right now I have to delete and re-add things. :(

Please?

**Comment by j0ri500** [comment]
It would also be nice to be able to deactivate timers instead of always having to delete them and add them again.

**Comment by BloodyIron** [comment]
Agreed

**Comment by robsdedude** [comment]
While working on [this](https://github.com/PhantomBot/PhantomBot/pull/2528) I considered adding the ability to re-order timers. My main problem with this is that I couldn't find a good form of interaction/input for it. Drag and drop is barely an option when combined with pagination. And having to specify say a position as number is cumbersome. I couldn't come up with a smooth UX so I didn't tackle it (for now). But I agree that having that feature would be nice. Just not sure how it should look like.

**Comment by gmt2001** [comment]
https://datatables.net/extensions/rowreorder/
