### ISSUE TITLE
[Feature Request] Loyalty Ban

### ISSUE THREAD

**Issue by rembomy** [PhantomBot/PhantomBot#2469]
Ability to ban people from gaining points or loyalty hours (keep them at 0 all times). 

Use case: Twitch bot accounts that are on your channel & streamer account so you wont show up in the leaderboards.

**Comment by mkleemann** [comment]
Please try the !ignoreadd command on these bots and after it !reloadbots. You also can add them directly in the ignorebots.txt.

Except for org.mozilla.* users it works fine.
