### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mrcsdl** [PhantomBot/PhantomBot#2499]
iam still trying to deploy the phantombot docker nightly.
So far it works but when i try to mount the folder to my host its not working
current mount point is /var/lib/docker/volumes/123_PhantomBot_data/_data
my mountpoint i want is /home/marc/apps/Bot/
but when i do this the container is not starting and just giving errors 

java.io.FileNotFoundException: ./logs/core-error/16-06-2021.txt (No such file or directory)

    at java.base/java.io.FileOutputStream.open0(Native Method)

    at java.base/java.io.FileOutputStream.open(Unknown Source)

    at java.base/java.io.FileOutputStream.<init>(Unknown Source)

    at java.base/java.io.FileOutputStream.<init>(Unknown Source)

    at com.gmt2001.Logger.run(Logger.java:132)

    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LyeosMaouli** [comment]
`(No such file or directory)` usually means you either put the wrong path or you have a permission issue.
It's the same as you already asked : [https://github.com/PhantomBot/PhantomBot/issues/2496#issuecomment-861382299](https://github.com/PhantomBot/PhantomBot/issues/2496#issuecomment-861382299)
Also, you should take a look at [Docker Volumes](https://docs.docker.com/storage/volumes/).

**Comment by mrcsdl** [comment]
yeah but my last request jsut got closed. I copyed the rights from the folder that is working but it dosent work

**Comment by LyeosMaouli** [comment]
I was close because it was answered, I think.
If you don't care about security or want to try if it's a permission issue you can do `chmod -R 777 /path/to/your/folder`.

**Comment by mrcsdl** [comment]
i tryed this already and it didnt worked for me
