### ISSUE TITLE
Docker persistent data

### ISSUE THREAD

**Issue by Khyretos** [PhantomBot/PhantomBot#2504]
i want my config folder to be persistent but i cannot get it to work, if i start the docker image with all the default files it works but when i try to make a volume like this :       `- ./PhantomBot/data:/opt/PhantomBot_data`
it gets this error:

`phantombot-stable | [07-05-2021 @ 16:13:26.616 GMT] The working directory is: /opt/PhantomBot
phantombot-stable | [07-05-2021 @ 16:13:26.668 GMT] Detected Java 11.0.4 running on Linux 5.4.0-77-generic (amd64)
phantombot-stable | [07-05-2021 @ 16:13:26.719 GMT] 
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | [07-05-2021 @ 16:13:26.746 GMT] PhantomBot Version: 3.4.2 (stable)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | [07-05-2021 @ 16:13:26.747 GMT] Build Revision: bf69ab8
phantombot-stable | [07-05-2021 @ 16:13:26.747 GMT] Creator: mast3rplan
phantombot-stable | [07-05-2021 @ 16:13:26.747 GMT] Developers: gmt2001, Kojitsari, ScaniaTV, & IllusionaryOne
phantombot-stable | [07-05-2021 @ 16:13:26.748 GMT] https://phantombot.github.io/PhantomBot/
phantombot-stable | [07-05-2021 @ 16:13:26.748 GMT] 
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
phantombot-stable | java.io.FileNotFoundException: ./logs/core-error/05-07-2021.txt (No such file or directory)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open0(Native Method)
phantombot-stable | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
phantombot-stable | 	at com.gmt2001.Logger.run(Logger.java:132)
phantombot-stable | 	at java.base/java.lang.Thread.run(Unknown Source)
`

i just want my config folder to be persistent and nothing else, any ideas?

**Comment by gmt2001** [comment]
A properly setup _docker-compose.yml_ has been provided both here and on Docker Hub for a reason

**Comment by Khyretos** [comment]
> A properly setup _docker-compose.yml_ has been provided both here and on Docker Hub for a reason

sorry i dont understand what you mean by this, the bot works with the default info i just want the folder that contains my commands gifs and sounds to be persistant, is this possible? if yes how can i achieve that?

**Comment by gmt2001** [comment]
Step 1: Use _docker-compose.yml_ exactly as it was designed instead of making random modifications to a system you don't understand. Docker already does this for you if you use the included _docker-compose.yml_ properly

Step 2: https://lmgtfy.app/?q=linux+create+symlink+to+directory

**Comment by Khyretos** [comment]
> Step 1: Use _docker-compose.yml_ exactly as it was designed instead of making random modifications to a system you don't understand. Docker already does this for you if you use the included _docker-compose.yml_ properly
> 
> Step 2: https://lmgtfy.app/?q=linux+create+symlink+to+directory

thank you for the clarification that it is a symlink and its my decision to make 'random modifications' i don't know why you have to be so rude about it but it seems part of your M.O i guess.

i will close this issue thanks again.
