### ISSUE TITLE
[Feature Request] Add / Remove Twitch Roles via PB Webpanel

### ISSUE THREAD

**Issue by TheBlackHawk1337** [PhantomBot/PhantomBot#2509]
Detailed Description:

It would be nice to add and remove Twitch Roles like VIPs, Mods and Editor via the Webpanel

**Comment by gmt2001** [comment]
Sorry, the Twitch API only allows us to give you a list of users currently in those roles, but not to add/remove them.

**Comment by dungi** [comment]
Little workaround: Just say ".vip user" or ".unvip user" to add or remove them. They should be automatically be removed from the VIPs roles.

**Comment by Sartharon** [comment]
This could still be added to the panel in making the bot say .vip <UserName> or .unvip <UserName> i guess but then there is still no list to choose users from which kinda destroys the whole point of adding it to the panel anyway (imo)

**Comment by gmt2001** [comment]
The bot does not have `chat:edit` on the broadcaster, which is the only user allowed to execute those commands, unless you use the broadcaster as the bot account, which is a fringe use-case

**Comment by dungi** [comment]
There should be no list, cause the list would be endless. The list of vips can be found in our Twitch Dashboard under Roles.
