### ISSUE TITLE
infinity redirect with 301 if usehttps enabled behind a reverseproxy and balancer like traefikv2+apache2

### ISSUE THREAD

**Issue by alimuratgymn** [PhantomBot/PhantomBot#2536]
PhantomBot Version: 3.5.0-NB-08052021 (nightly_build, Docker) (Revision: 882a98b)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related): 1.5.0
Apache2: 2.4.46
Traefik v2: 2.4.13

--

**Detailed Description:**
If PhantomBot is running behind a loadbalancer and reverse proxy like apache2 with Traefikv2 and with usehttps enabled in phantombot, phantombot produces a infinity redirect with 301 (screenshot) . And if usehttps is disabled the ui checks over js for /sslcheck and gets false returned even if the request is over https and everything looks fine.

--

**Steps to Reproduce:**
Run PhantomBot behind Traefik with Docker-Compose and usehttps: enabled
The reverse Proxy has forward header ssl host and proxyheaders is set

--

**Example Request:**
```
Request <-https-> internal load balancer (apache2) <-http-> Traefikv2 <-> Phantombot
```

--

**My temporary Workaround:**

1. Disable USEHTTPS for PhantomBot
2. Intercept /sslcheck path with apache2 or something else
3. return a true instead of false

**Logs/Screenshot:**
The redirected URL is the same URL where the Phantombot/Traefik/Apache is accepting requests.
![grafik](https://user-images.githubusercontent.com/22096341/128610559-553a779e-e871-42f9-bf6e-94c1dcad86ea.png)

**Comment by gmt2001** [comment]
HttpSslRedirectHandler only fires if you attempt to connect using `http://` (non-ssl url) when https is enabled

**Comment by alimuratgymn** [comment]
hey, thats basically fine but if i disable usehttps to make it work behind the reverseproxy the phantombot-ui blocking the login because of the sslcheck. i think there is a little bit improvement potential in the login form or in HTTPNoAuthHandler to better check if the connection is https instead of just checking if the https setting is enabled or disabled

**Comment by FlikstRR** [comment]
I have this same issue and had to simply skip that sslcheck for mine to work. index.js line 20.


![image](https://user-images.githubusercontent.com/1532321/128616254-7fc47148-17a2-4b0f-9119-283fe573deec.png)

**Comment by gmt2001** [comment]
The issue is there is not necessarily a standardized way to get that information from a reverse proxy.

It can vary widely depending on the software used and configuration.

The best solution may be to just redirect `/sslcheck` to a simple webpage that has the word `true` which is what the bot does.

We should probably add instructions for this to the guides.

**Comment by gmt2001** [comment]
I suppose I can look into the idea of adding an `override` value to _usehttps_ or something that makes `/sslcheck` perform a false-positive for this

**Comment by alimuratgymn** [comment]
hey again, thats also right there is no standardized way to build a system with a reverse proxy but the communication from inside to inside is mostly http, maybe its possible for you to add a additional reverseproxy setting to make HTTPNoAuthHandler return true or something else, imo it would be the clean way to go.

--

my workaround as i mentioned also redirects /sslcheck to return true i did it with apache2 in the specific vhost

--

**_Workaround in Apache Vhosts_**
```
<Location /sslcheck>
    ErrorDocument 200 "true"
    RewriteEngine On
    RewriteRule .* - [R=200]
</Location>
```

**Comment by AlphaYankee** [comment]
There's no need to invent something for this, there's a standard headet the proxy should send (X-Forwarded-Proto: https) which could then be checked for. If you don't check that the request comes from the correct proxy IP this could be faked if PhantomBot is not behind a proxy, but it's more of a convenience function so I don't think that's an issue.

Also there is a new RFC for a new header "Forwarded" but I haven't seen that in use, a description is [here](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/).

**Comment by alimuratgymn** [comment]
according to my observation the application does not check these flags properly otherwise my setup would have worked i use the appropriate headers as already mentioned.

**Comment by gmt2001** [comment]
Use `proxybypasshttps=true` in _botlogin.txt_ in the latest nightly
