### ISSUE TITLE
Feature Request: Anounce Other Live Channels in Discord Like StreamCord.io

### ISSUE THREAD

**Issue by scify666** [PhantomBot/PhantomBot#2539]
It would be a very nice feature to anounce a list of selectet channels in Discord. Or is there any extention?

**Comment by SetCr4** [comment]
You might want to look at the command `!promoteadm` on the build-in discord command list:
https://phantombot.github.io/PhantomBot/guides/#guide=content/commands/discord-commands
CTRL+F → "promoteadm"
