### ISSUE TITLE
Promote system issues when on version 3.4.7 - !promoteadm - 3.4.2 it is stable

### ISSUE THREAD

**Issue by worldofmadness** [PhantomBot/PhantomBot#2546]
PhantomBot Version: 3.4.7 - Rolled back to 3.4.2
O/S Version: Docker Linux or windows
Java Version:
Web Browser Version (if Panel related):

Detailed Description:

i use the promote system  which announces the who's live etc using the command !promoteadm

when i updated from 3.4.2 to 3.4.7 and the system went super sideways will show image links of the differences.

3.4.2 shows how the system looks and works below

[https://ihostimages.uk/images/2021/08/13/DiscordPTB_arT2P9bF6Z.png](https://ihostimages.uk/images/2021/08/13/DiscordPTB_arT2P9bF6Z.png)

only shows steams once when they go live

3.4.7 shows what happened when it was updated

updating ever 6 mins and repeating over and over the streams live

[https://ihostimages.uk/images/2021/08/13/DiscordPTB_WSEN1VksPs.png](https://ihostimages.uk/images/2021/08/13/DiscordPTB_WSEN1VksPs.png)
 as you can see the follows have stopped working the banner isn't pulled and they repeat many times 

Steps to Reproduce:

update to 3..4.7 and it goes multiple and info missing 

downgrade back to 3.4.2 all goes back to working and normal

Logs:

no logs or errors

Screenshots (if applicable):

see above can send more if needed

**Comment by TheSyntox** [comment]
Yes, I'm having exactly the same issue. Tried a couple of things but nothing works. On top of that, those messages are posted even if I disable  ./discord/systems/promoteSystem.js module (I assume that's the one for !promoteadm).

**Comment by dirksade** [comment]
I noticed that the multiple announcements are also happening after the automatic oauth token is refreshed as well.

**Comment by Phr3d13** [comment]
I can confirm that this is still an issue with 3.5.1
