### ISSUE TITLE
Raid count is wrong (including a suggested fix)

### ISSUE THREAD

**Issue by therentabrain** [PhantomBot/PhantomBot#2566]
_First time poster - please let me know if I don't follow protocol!_
PhantomBot Version:  3.4.7 (it would be great if this showed on the main ctrl panel!)
O/S Version:  Windows (cough) 7
Java Version:  11.0.4+10-LTS

Detailed Description:

Raid count is one fewer than it should be, based on the sentence.

Steps to Reproduce:

Someone raids for the first time.  The message shows as "[user] is raiding us with [count] viewers!"

Someone raids for the second time.  The (times) variable reports "This is the 1 time [user] has raided us!"

Suggestion (line 189 of raidHandler.js):

                message = $.replace(message, '(times)', parseInt(raidObj.totalRaids) + 1);

Also, the grammar could be better.  I humbly suggest:

"They have raided us (times) times!"

**Comment by UserModel** [comment]
@gmt2001 Can I pick this bug up?

**Comment by gmt2001** [comment]
Go for it.

Please [tag this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) in either the commit message or the pull request description when you send it in

**Comment by therentabrain** [comment]
Thank you!

**Comment by UserModel** [comment]
Great, I just submitted a PR. Regarding the grammar changes @therentabrain, you can change what the raid message says under the alerts tab, click raid settings, and there you can change the different messages!
