### ISSUE TITLE
Twitch APIv5 Deprecation

### ISSUE THREAD

**Issue by arcreigh** [PhantomBot/PhantomBot#2575]
https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

Got a notice today that phantombot is using the v5 API and that twitch is removing v5 in the near future.

**Comment by gmt2001** [comment]
Already resolved in PhantomBot v3.4.7

If you were not fully upgraded by August 1, 2021 you may have gotten this notice anyway

**Comment by arcreigh** [comment]
That'd do it! Thanks!
