### ISSUE TITLE
Recent Events broken again

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2578]
PhantomBot Version: 3.5.0-NB-10242021 (nightly_build) (Revision: 9a87458)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):

Detailed Description:
The Recent Events panel weirdly lists a list of followers at its end.
Below the other events is a list of only follower events occuring. For instance, someone cheered today and should be the latest event but the latest event is a follower from the first of October.
I think it is just something with the sorting. The events are sorted correctly and followers are displayed correctly but there is a list of purely followers at the end in reverse order sorted by date.
It worked with the last nightly build^^

It's like:
- [Everything sorted correctly]
- Cheer from today
- List of followers
- Follower from October first

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
If you get tomorrows nightly, it should happen one more time, but then be fixed after that
