### ISSUE TITLE
Bot resets game

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2583]
PhantomBot Version: 3.5.0-NB-11072021 (nightly_build) (Revision: 53cb050)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):

Detailed Description: When I start streaming, the bot usually posts on Twitter with the wrong game and later on posts a "game changed to"-tweet.
Sometimes, however, the bot resets the game to the last one played (e.g. was "just chatting" and will be changed to "Guild Wars 2"). Maybe the bot could pull the game from twitch when detecting that a stream is online and posts after updating itself?
I really don't know what causes the bug. If I set the game a certain time beforehand, this does not happen.
I've tried to set the game the day before -> works
I've tried a few minutes beforehand -> doesn't work

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
The bot already uses TwitchAPI to detect the game. I will look to see if there is a way to make it more reliable though

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/PhantomBot/issues/2421
