### ISSUE TITLE
!twitter returns wrong link

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2585]
PhantomBot Version: 3.5.0-NB-11072021 (nightly_build) (Revision: 53cb050)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):

Detailed Description: When twitter is connected and !twitter is used, the returned link contains the ] within the link. Seems like an easy fix with just a typo being in there :)

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/PhantomBot/issues/2421
