### ISSUE TITLE
Enhancements for (count)

### ISSUE THREAD

**Issue by nerdyjohnny** [PhantomBot/PhantomBot#2587]
PhantomBot Version: 3.4.7
O/S Version: Debian 10
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related): 1.40

Detailed Description: More of a request. Add the ability to just display (count), subtract from (count), and set the numerical value for (count)

Steps to Reproduce: N/A

Logs: N/A

Screenshots (if applicable):

**Comment by piebandit** [comment]
An additional enhancement I think would be nice to have, is a command variable to only display the count and not increase it. I guess the idea would be for like a custom death counter that could be used for anything, like keeping count of runs where mods can increase or adjust the count while viewers can use a command to only show the count.

(count command:str) for example.
