### ISSUE TITLE
[Bug] Refreshing poll URL, while poll is active, shows nothing

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2591]
PhantomBot Version: 3.4.7
O/S Version: Ubuntu 20.04
Java Version: Included
Web Browser Version (if Panel related): Agnostic of this

So this issue doesn't seem tied to a specific version. I'm trying to tune the CSS styling for the Poll website in OBS, and whenever I make changes it reloads the page for the poll. Now, when I reload the same page in my browser it does the same thing. What happens is that the page is now blank (as in, no data shown), when previously the poll was actually displayed right there. The poll is still running, so this is rather problematic.

What I would like to see, instead, is every time you load the Poll URL, whether in my browser, OBS, or whatever, I get the current state of the poll. So if I reload the URL for whatever reason, I don't have to restart the poll.

**Comment by gmt2001** [comment]
IIRC this is already in the nightly that I am looking to release as the next stable as soon as we tackle the major bugs in the release candidate

**Comment by BloodyIron** [comment]
Yay! \o/ Should we close this ticket or?

**Comment by gmt2001** [comment]
I checked and I did indeed put that feature in nightly, closing

**Comment by BloodyIron** [comment]
@gmt2001 yay! Thanks for checking and the work! Can't wait to get the next release :)

**Comment by BloodyIron** [comment]
OMFG 3.5 RELEASED LITERALLY ONE MINUTE AGO OMGOMGOMGOMGOG

**Comment by BloodyIron** [comment]
@gmt2001 confirmed this issue appears to be fixed in testing! Just waiting for poll themeing then I can start using this :D
