### ISSUE TITLE
[Bug?] Can't find version in webGUI

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2592]
PhantomBot Version: All

Hey so I can't for the life of me find a way to check the version of PB in the webUI. Can we please have this placed somewhere stupid easy to find?

I can, if absolutely needed, go to console and all that to find it. But this seems like something that's a good idea to do.

**Comment by gmt2001** [comment]
The last category on the left menu of panel should be like _help_ or _support_ or something like that. That page should have it

**Comment by BloodyIron** [comment]
@gmt2001 OMFG I forgot that section. Seriously was hunting for it so hard yesterday. DISREGARD.
