### ISSUE TITLE
[Bug] "New" phantombot release detected (old version)

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2598]
PhantomBot Version: 3.5.0
O/S Version: Ubuntu 20.04
Java Version: Included

Just updated to v3.5.0 of PhantomBot and the console and webGUI is telling me there's a new version! As in... v3.4.7, the one I just updated from hehehe. Bug? ;)

**Comment by gmt2001** [comment]
Apparently GitHub doesn't sort releases in the API in order DansGame

**Comment by BloodyIron** [comment]
LOL well hopefully this "helps" or sometihng XD <3

**Comment by mesosteros** [comment]
Can confirm this on Windows 10 as well. I copied the config folder over from the previous version per the instructions on the Release Notes.
![image](https://user-images.githubusercontent.com/1943233/142838685-28f99c78-3b09-4b83-95af-ef6ea6c9a8ca.png)

**Comment by gmt2001** [comment]
Yeah, I checked the raw output from GitHub API and apparently for some stupid reason the releases are not in proper order. Then when I googled the issue the response someone else was given was _well we don't guarantee any order at all_ which is BS

So now I'll have to add dedicated logic for absolutely no reason to parse the entire list of releases, convert the text-based dates into workable date objects, and compare them to find the latest release

**Comment by BloodyIron** [comment]
@gmt2001 so far this issue appears resolved! Yay, thanks! :D
