### ISSUE TITLE
[Bug, v3.5.0] Polls throwing error (failed to dispatch event)

### ISSUE THREAD

**Issue by BloodyIron** [PhantomBot/PhantomBot#2599]
PhantomBot Version: v3.5.0 (as of right now)
O/S Version: Ubuntu 20.04
Java Version: Included

Just updated to v3.5.0 to hopefully get the Poll improvement, but it's now broken, and this is what the bot log spits out whenever I start a poll:

[ERROR] [handleError()@ExceptionHandler.java:26] Failed to dispatch event [public void tv.phantombot.script.ScriptEventManager.onEvent(tv.phantombot.event.Event)] to [tv.phantombot.script.ScriptEventManager@57fd91c9] null

Seems to happen every time. I'm running this in a VM, not docker.

**Comment by gmt2001** [comment]
Does it still work though?

**Comment by BloodyIron** [comment]
So far as I can tell in multiple testing, the Poll graphic does not display on the page. I only tested with my browser, not in OBS. But I tried the poll two different times (with 0 and arbitrary time length), both times the graphics did not draw at all on the display URL page.

However, the chat aspects and other functionality seem to work, but I didn't test that too deeply.

**Comment by BloodyIron** [comment]
Just added an edit to my response, since I see you're working on this in real-time. :) <3

**Comment by gmt2001** [comment]
Identified as mozilla/rhino#450. Fixed in mozilla/rhino#875. Here's to hoping that upgrading the version on this POS doesn't break too much LUL

**Comment by BloodyIron** [comment]
I suspect this same issue is causing issues with the Timing module too, as my bot would not shut up the other day, even though I disabled timing to try to shut it up. It was supposed to post a text once enough people had chatted (and after a set amount of time), but it kept just posting after the time limit, when nobody was chatting. Toggling Timing off, the bot kept chatting anyways, after the set amount of time.

**Comment by BloodyIron** [comment]
@gmt2001 confirmed that this issue is solved with v5.0.1 update! Not getting the issue!
