### ISSUE TITLE
bot not starting up with error systems/noticeSystem.js: Syntax Error unexpected token: /

### ISSUE THREAD

**Issue by richardk-dbs** [PhantomBot/PhantomBot#2603]
PhantomBot Version: 3.5.0.1 and 3.5.0.1-NB-11242021
O/S Version: Debian 10
Java Version: 11.0.11

Detailed Description:

Bot was working fine all the time. Now when starting up the bot via docker-compose up i can see the following error:

```
phantombot-stable1 | [11-26-2021 @ 16:35:33.520 GMT] [ERROR] [loadScript()@ScriptManager.java:46] Failed to load module: systems/noticeSystem.js: SyntaxError: Unexpected token: / (noticeSystem.js#57)
phantombot-stable1 | [11-26-2021 @ 16:35:33.521 GMT] [ERROR] [loadScript()@ScriptManager.java:50] Terminating PhantomBot due to Bad JavaScript File
```

After this error the bot is shutting down.

I tried with stable and with nightly build, no change.

I then checked the database via sqlite3 and I can see, that the notice handler is set to false.

What can I do to debug and fix that? Any help is really appreciated.

the docker-compose.yml is basically exactly as the sample yml from docker hub, just the oauth tokens are commented out because of the automatic refresh

**Comment by gmt2001** [comment]
That is quite strange. I don't see a `/` anywhere near that line in the file. Will need further investigation

**Comment by gmt2001** [comment]
If possible. Try grabbing the file out of the container and comparing it to

https://github.com/PhantomBot/PhantomBot/blob/6e2bfcc63d31de75adfda83b3ed3a041782289a3/javascript-source/systems/noticeSystem.js

**Comment by richardk-dbs** [comment]
I made an export of the container via docker export.
I downloaded the file from the export and also the file from github.
the only difference of both files is that after the last line I have an empty line in the file from github which I dont have in the file from my container.

**Comment by gmt2001** [comment]
I spun up a brand new container using the exact docker-compose listed on Docker Hub at https://hub.docker.com/r/gmt2001/phantombot-nightly and had no issues. This is very strange that it is doing this to you and I am not sure what to do about it at the moment. As a temporary fix you should be able to `docker cp` the copy from GitHub into the container to replace the bad one

**Comment by richardk-dbs** [comment]
ok, that is indeed really strange. 
Do you mean to replace only the noticeSystem.js ?

**Comment by richardk-dbs** [comment]
ok, found the issue and a solution.

In the table notices, there was an entry which was used in the past. This notice included an URL which should be posted all x minutes. This entry was causing the noticeSystems.js to not load, even if the noticeSystem was not active. On line 57 of noticeSystem.js it pulls the existing notices from the database.

So I went to the folder of the PhantomBot_Data/config inside of the docker volume for the PhantomBot_Data Folder, which is located at /var/lib/docker/volumes

the I used sqlite3 phantombot.db and executed following commands

SELECT * FROM phantombot_notices;

to check what is stored in the table notices

then I issued the command 

DELETE FROM  phantombot_notices;

to empty this table ( as I did not need any notices, I deleted all entries)

Now the container is starting up again.


Why I was able to add this notice without issue and have those issues afterwards, I dont know. 

Thanks for the help in any case!

**Comment by gmt2001** [comment]
I'm going to keep the issue open. I need to look into figuring out why it is doing that and see if I can fix it

**Comment by ZyanKLee** [comment]
I got a similar problem with versions 3.5.0.2, 3.5.0.3 and current nightly image:
```
Failed loading "./systems/noticeSystem.js": SyntaxError: Unexpected token: F
```
though it does not terminate anymore.

**Comment by gmt2001** [comment]
If you are comfortable with it, could I possibly have a copy of your phantombot.db file that is having this issue so I can investigate more thoroughly?

**Comment by gmt2001** [comment]
Closing as stale. If it happens again, please re-open and include a copy of the offending _phantombot.db_
