### ISSUE TITLE
[linux] symlinks to files fail to play -- alerts

### ISSUE THREAD

**Issue by arrowgent** [PhantomBot/PhantomBot#2614]
PhantomBot Version: PhantomBot Version: 3.5.0.1 (stable)
O/S Version: linux
Java Version: Detected Java 11.0.11 running on Linux 5.4.0-91-generic (amd64)

Detailed Description:

for playsound and audio_hook commands
creating symbolic links to files (audio) fails to play
`ln -s file.mp3 file1.mp3`
audio does not play with play button in audio_hooks panel

Steps to Reproduce:

`ln -s file.mp3 file1.mp3`
refresh audio_hooks
file1 audio does not play with "play" button in audio_hooks panel
create audio command !file1 using linked file
type in chat `!file1`
nothing plays

2nd
create custom command !file1 == `(playsound file1)`
output in chat is (playsound file1) instead of playing the audio file

this might effect other alerts such as gif / video files
i have not tested those yet

**ALSO**, if a file is missing or "typed incorrectly" the custom command output will be`(playsound missingfilename)`

**Comment by arrowgent** [comment]
confirmed for alert

`ln -s file.gif file1.gif`
`ln -s file.mp3 file1.mp3`

set follower message:
`(name) followed (alert file1.gif, 10, 1, test, (name) followed )`

the gif & mp3 does not play, it shows `[]video` in place
atleast the chat response doesnt show (alert file1.gif ---etc

**Comment by gmt2001** [comment]
Any path which leads out of the intended folders is intentionally blocked for security reasons

**Comment by arrowgent** [comment]
they are in the same folder

**Comment by gmt2001** [comment]
Then there is no reason to use a symlink

**Comment by arrowgent** [comment]
i suppose you could say that

in linux, most libraries are symlinked such as:
```
libstdc++.so.6 -> libstdc++.so.6.0.28
libstdc++.so.6.0.28
```

i dont know the reasoning for allowing symbolic links such as this for critical system files
and not a java bot running locally without http:80 https:443 access (firewalled)


my reasoning was to rename files without losing their original filename

file1.mp3 > sfx_title_sourcename_location_year_original_edited.mp3

also so i dont have to physically duplicate files between
Phantombot/config/audio-hooks
Phantombot/config/gif-alerts

if i can duplicate the file with a symlink and rename the link to match the "file.gif" + "file.mp3" requirement that would solve an issue of doubling 500mb of mp3 & gif files

instead of renaming everything to be matching such as:
banana.gif
banana.mp3

i could use symlink to pair a gif to a different mp3
follower_special_flying_animated.gif
follower_special_flying_animated.mp3 > sfx_play_old_funny_sfx_with_long_file_name.mp3

without symlink, duplicating filename.gif = filename.mp3 loses its source title
without symlink, i will end up doubling the disk space for gif/mp3


secondly, im working on an alert randomization edit to the alerts.js javascript
randomly choose a gif from /gif-alerts and randomly match it to an audio in /audio-hooks
but youre saying it cant read from this directory? files MUST be in the same directory even though they are on the whitelist of folders?

now for 4 randomized gifs playing with one mp3 it becomes
rand=
gif1.gif
gif2.gif
gif3.gif
gif4.gif
gif1.mp3
gif2.mp3
gif3.mp3
gif4.mp3

when it could have simply been
rand=
gif1.gif
gif2.gif
gif3.gif
gif4.gif
gif1.mp3
gif2.mp3 > gif1.mp3
gif3.mp3 > gif1.mp3
gif4.mp3 > gif1.mp3


while its fine if you think one gif and one mp3 is all anyone would need for follower,host,raid etc i would like to add functionality here

**though if this is a physical limit of java, that is fine also.  we cant re-write java to accept symbolic linking**
infact i know java can symlink a .jar file from any location on your directory tree
/home/user/.folder/file.jar > /usr/share/local/bin/file123456790.jar
works fine in java launch parameters.

**Comment by arrowgent** [comment]
also i should note

```
Phantombot/config/audio-hooks
Phantombot/config/gif-alerts
```

are both directories symlinked somewhere else on the disk
so, symlinks do work for folders ...
