### ISSUE TITLE
Startup Error?

### ISSUE THREAD

**Issue by Rosw3lluk** [PhantomBot/PhantomBot#2624]
PhantomBot Version: 3.5.0.3
O/S Version: Ubuntu 20
Java Version: (Included one?)
Web Browser Version (if Panel related): (Not Panel Related)

Detailed Description:
Hello, i have installed PhantomBot successfully thus far, and am attempting to edit tokens (e.g discord, twitter) and am editing the botlogin.txt file located within the config folder,

When the edits are complete, i save them in a local copy i have in my computer, the filesize goes from 909kb to 1267kb, i upload this file to the phantombot server, and confirm at time of upload the filesize is 1267kb,

I restart the Phantombot service using "sudo systemctl restart phantombot" and then it pauses for a second, i login to the control panel, and nothing has changed (e.g no discord options)

I refresh the view in my FTP client, and the botlogin.txt file seems to revert to the original installation file, where all my changes have vanished and goes back to the 909kb version.

Steps to Reproduce:

If its not isolated, simply edit your botlogin.txt file, restart the server and the changes seem to vanish and the file is replaced with a stock version.

Logs:
Can you let me know which logs you would require? and where to locate them

Screenshots (if applicable):

**Comment by gmt2001** [comment]
You can't edit files while the bot is running
