### ISSUE TITLE
[Bug] "Mass Gifted Subscription" Event Tag when only 1 sub is gifted

### ISSUE THREAD

**Issue by TheBlackHawk1337** [PhantomBot/PhantomBot#2634]
PhantomBot Version:  3.5.0.3 (stable) (Revision: 086078a)
O/S Version: Linux
Web Browser Version (if Panel related): 1.5.0

Detailed Description:
Noticed that at one gifted sub there is the tag for mass gifted subscription in panel eventlist
20.12.2021, 14:02:22 | Mass Gifted Subscription | username gifted subscriptions to 1 viewers at tier 2!

Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/47850314/146774214-dc8c0c16-d0b7-4417-b055-086a39103881.png)

**Comment by arrowgent** [comment]
that seems like twitch api is working correctly

if a gifter gives random subs to the community they are all reported the same, 1 or 100 gift subs are the same string response

i believe if the gifter selects a specific user in chat, it has a different api response
for random gift subs the twitch api reports the same string

**Comment by gmt2001** [comment]
If you saw the `User is gifting a tier 1 sub to a member of the community` message in chat from Twitch before the second message about the actual gift sub then it is as designed by Twitch
