### ISSUE TITLE
[Bug] Followage command is broken.

### ISSUE THREAD

**Issue by AlexanderCurl** [PhantomBot/PhantomBot#2639]
PhantomBot Version: 3.5.0.6
O/S Version: Ubuntu 20.04
Java Version: 11.0.11

Detailed Description:
In this version the `!followage` command has been broken. I was unable to trace back the issue.
I opened the issue, as several people, including me reported on Discord, so it won't get lost.

Steps to Reproduce:
1. Start the bot.
2. Type `!followage` in Twitch chat.

Logs:
```
[12-29-2021 @ 05:56:22.668 GMT] [ERROR] [init.js:340] Error with Event Handler [ircChannelJoin] Script [./core/permissions.js] Stacktrace [hasKey()@permissions.js:112 > userExists()@permissions.js:171 > permissions.js:746 > init.js:332 > init.js:654] Exception [TypeError: Cannot call method "equalsIgnoreCase" of undefined]
```

**Comment by gmt2001** [comment]
- [x] Replace with `$.equalsIgnoreCase`

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/javascript-source/core/permissions.js#L112

refs rb#1053

**Comment by AlexanderCurl** [comment]
No luck with that so far.. :(

**Comment by gmt2001** [comment]
Investigate GetUserFollowsChannel response

https://github.com/PhantomBot/PhantomBot/blob/0104f39479d520047d38140219f60d218e1474b0/source/com/gmt2001/TwitchAPIv5.java#L694-L711

- [x] Validate raw response on known non-follower
- [x] Validate raw response on known follower
- [x] Validate logical comparisons for known follower
- [x] Validate Helix-to-v5 translator for known follower data
- [x] Validate js handling of API response object

**Comment by gmt2001** [comment]
Currently unable to reproduce.

- Verify APIOauth is good
- Add/edit to _botlogin.txt_
```
debug=true
helixdebug=true
```
- Try again and post console logs

**Comment by gmt2001** [comment]
Closed as stale. If issue is still occurring, please try steps in above message
