### ISSUE TITLE
Unable to Login after switch to ssl

### ISSUE THREAD

**Issue by Dreandor** [PhantomBot/PhantomBot#2685]
PhantomBot Version:  3.5.0.8
O/S Version: Debian 10
Web Browser Version (if Panel related): Chrome, Opera GX

Detailed Description:
I can't login after the switch to ssl. I tried the Method 3 (https://phantombot.github.io/PhantomBot/guides/#guide=content/integrations/twitchembeds) with apache. I use KeyHelp for managing my server and I did in the subdomain statement's for https:
ServerName SERVERNAME
ProxyRequests On
ProxyPass "/ws/" "ws://127.0.0.1:25000/ws/"
ProxyPassReverse "/ws/" "ws://127.0.0.1:25000/ws/"
ProxyPass "/" "http://127.0.0.1:25000/"
ProxyPassReverse "/" "http://127.0.0.1:25000/"
ProxyPreserveHost On

Steps to Reproduce:
Install KeyHelp on Debian 10. Add an subdomain and install PhantomBot, then try to switch to ssl with Method 3

Logs:
WebSocket connection to 'wss://SERVERNAME/ws/panel/login?target=SERVERNAME:443' failed: Error during WebSocket handshake: Unexpected response code: 500

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Did you change `usehttps` to false and add `proxybypasshttps=true` to _botlogin.txt_, while the bot was shutdown?

**Comment by Dreandor** [comment]
Yes
![image](https://user-images.githubusercontent.com/6794796/157914878-2305a6e4-b1c5-44e3-aabf-7d77e4d3a050.png)

**Comment by gmt2001** [comment]
Try adding `LogLevel proxy:trace5` to your httpd configuration and then issuing a `reload` command to httpd. Then try again. It should put a lot of debugging information into your httpd logs so we can see where exactly the failure is coming from

**Comment by Dreandor** [comment]
I fixed it. proxy_wstunnel wasn't activated.
