### ISSUE TITLE
Discord Module Broken

### ISSUE THREAD

**Issue by ICEconchy** [PhantomBot/PhantomBot#2691]
PhantomBot Version: 3.5.2.2 (stable) (Revision: 935c83c)
O/S Version: Linux
Java Version: 11.0.14.1+1-LTS
Web Browser Version (if Panel related): Firefox 98

Detailed Description:
Discord bot does see chat messages in console but does not reply/execute modules. 

Steps to Reproduce:
Use latest version and follow guides to enable discord, Create command or use default module for example 8ball or kill

Logs:
Unsure which logs to give

Screenshots (if applicable):
N/A

**Comment by gmt2001** [comment]
![image](https://user-images.githubusercontent.com/3355471/158266829-558db332-dabb-475e-a719-f0111fe230c5.png)

**Comment by ICEconchy** [comment]
![image](https://user-images.githubusercontent.com/20145992/158267007-11da6eeb-86b8-4a8f-a800-5f4ab8aa32d5.png)

Nuffin happens, even though its all setup. Bot is in discord, bot announces streams

**Comment by gmt2001** [comment]
Check `core-error`, `core-warnings`, and `error` logs for Discord stuff

**Comment by ICEconchy** [comment]
![image](https://user-images.githubusercontent.com/20145992/158268417-37dc9702-7fc5-43e4-a07a-1f6c321a85ed.png)
Well that seems wrong...

**Comment by gmt2001** [comment]
Grab the console output, including after sending a message

**Comment by ICEconchy** [comment]
Console output before message: https://pastebin.com/PVD8e1UA

After message:
[03-14-2022 @ 22:47:44.190 GMT] [DISCORD] [#bot-torture] [CHAT] <@106439757130633216>, Usage: !module [enable / disable / list]
[03-14-2022 @ 22:47:52.658 GMT] [DISCORD] [#bot-torture] iceconchy: !pp
[03-14-2022 @ 22:47:57.654 GMT] [DISCORD] [#bot-torture] iceconchy: !gimmescp

So !gimmescp and !pp were both created before which do not get a response. The default module one appears to work.
I'm guessing its something to do with the service?

**Comment by gmt2001** [comment]
Try re-creating them

**Comment by ICEconchy** [comment]
Recreated. Not working, no response but console picks it up

**Comment by gmt2001** [comment]
Try running `!channelcom !pp --global` in Discord then see if that changes anything for `!pp`

**Comment by ICEconchy** [comment]
That fixed it. 

(On a side note, is there any variables for discord? I don't think that part of the guide is complete)

**Comment by gmt2001** [comment]
You had used `!channelcom` in the past to restrict the command to a specific channel

```
(1)...(9)
(1=default)...(9=default)
(customapi)
(customapijson)
(touser)
(touser=default)
(sender)
(@sender)
(random)
(#)
(# min,max)
(status)
(game)
(uptime)
(echo)
(viewers)
(follows)
(readfile)
(readfilerand)
(count)
(writefile)
(lasttip)
(encodeurl)
(setrole user,role)
```

**Comment by ICEconchy** [comment]
I haven't used the channelcom command at all.

**Comment by ICEconchy** [comment]
Also, apparently, variables aren't working either? Got anything to fix that?
