### ISSUE TITLE
SQL Corruption

### ISSUE THREAD

**Issue by ICEconchy** [PhantomBot/PhantomBot#2719]
PhantomBot Version: 3.5.2.2 (stable) (Revision: 935c83c)
Operating System: Linux
Java Version: 11.0.14.1+1-LTS
Web Browser Version (if Panel related): Firefox 98

Detailed Description:
SQL error found in logs. Unsure why they were generated, unsure how to fix

Steps to Reproduce:
Unknown

Logs:
https://www.toptal.com/developers/hastebin/ixonabowas.sql

Screenshots (if applicable):

**Comment by IceFlom** [comment]
The SQLite database seems to be broken. Have you tried to stop the bot, get a SQLite file from the backup folder and start with that? Maybe there is still a working backup there.

**Comment by ICEconchy** [comment]
This is from the backup.... T_T

**Comment by IceFlom** [comment]
That's bad. 😕 
I don't think it has to do with the PhantomBot itself, but simply the SQLite database is inconsistent.
I would try to open the database with a tool like "DBBrowser for SQLite", export the data there to an sql file and then create a new database and import the data again. Maybe you can save the data this way.

DBBrowser tool: https://sqlitebrowser.org

**Comment by Ismailovpro** [comment]
Need Incognito viewers for bigotv, is possibly?
