### ISSUE TITLE
SQLite 3.36.0.3 crash on Raspbian Buster

### ISSUE THREAD

**Issue by Donzii** [PhantomBot/PhantomBot#2728]
PhantomBot Version:
3.5.2.3

O/S Version: 
Raspbian GNU/Linux 10 (buster) (10.12)
Linux raspi4 5.15.27-v8+ #1531 SMP PREEMPT Wed Mar 9 11:36:50 GMT 2022 aarch64 GNU/Linux

Java Version:
OpenJDK Runtime Environment (build 11.0.14+9-post-Raspbian-1deb10u1)

Detailed Description:
PhantomBot crashes due to the sqlite libray not loading correctly or at all.
I was able to pin it down to the version 3.36.0.3 of sqlite-jdbc-3.36.0.3.jar.
3.5.0.11 still comes with sqlite-jdbc-3.31.1.jar, which does not have this problem.

Steps to Reproduce:
Launch any PhantomBot versions since 3.5.1 on a Raspberry Pi 4 running Raspbian Buster.

Logs:
```
OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.36.0.3-fe456dd6-858b-46a2-9b88-6a9293534094-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.36.0.3-fe456dd6-858b-46a2-9b88-6a9293534094-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-fe456dd6-858b-46a2-9b88-6a9293534094-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-fe456dd6-858b-46a2-9b88-6a9293534094-libsqlitejdbc.so: falsche ELF-Klasse: ELFCLASS64 (Possible cause: architecture word width mismatch)
Failed to load native library:sqlite-3.36.0.3-724d2e36-4ba5-456a-a310-c37d919857b2-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-724d2e36-4ba5-456a-a310-c37d919857b2-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-724d2e36-4ba5-456a-a310-c37d919857b2-libsqlitejdbc.so: falsche ELF-Klasse: ELFCLASS64 (Possible cause: architecture word width mismatch)

```

**Comment by arrowgent** [comment]
might be related to Buster (debian10) vs Bullseye (debian11)
while buster does have extended support,  you should be moving to bullseye indefinitely.  so long as you intend to maintain newer versions of software on the older OS...  older versions of phantombot etc would continue to work fine
https://endoflife.software/operating-systems/linux/debian ~ August, 2022

also `ELFCLASS64` means the libsqlitejdbc.so was compiled for arm64
your version aarch64 ... should be compatible here...

it could also be a build/compile error,  being built against the newer distro packages which would fail on older distros.

`    runs-on: ubuntu-latest`
might be pulling 22.04 jammy before its stable... unknown on the build scripts of github yaml

**Comment by gmt2001** [comment]
I would recommend switching to H2

Just open or create `config/botlogin.txt` while the bot is shutdown and put a line in there that says `datastoretype=h2store`

I can't explain why it worked before and not now

To preserve your existing database, you should make this change on version 3.5.0.11, then run the bot for about 5-10 minutes before shutting it down and upgrading

**Comment by Donzii** [comment]
> 
@arrowgent 
We are talking not about Debian, its Raspberry Pi OS
(Raspberry Pi OS (Legacy) will remain supported while the various components continue to receive updates. For Debian Buster, support will be available until June 2024. For Linux 5.10 kernel, December 2026. If Debian Bookworm becomes stable in this time, Raspberry Pi (Legacy) will switch to Bullseye.
https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/ )
I have compatibility problems with v1 and v2 Raspi-Cams, i can switch to Bullseye, if the Bugs are gone. my rasps are more than a tiny-pc, they are nas and nightwatchers

@gmt2001 
i will try it and will responce

**Comment by gmt2001** [comment]
Not sure where you got on this but I saw a potential fix proposed on the repo for the library

Unfortunately, the maintainer appears to be on Hiatus, so I will have to try to get the build pipeline working for my own fork, but I want to look into this soon
