### ISSUE TITLE
DOCKER {"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}

### ISSUE THREAD

**Issue by worldofmadness** [PhantomBot/PhantomBot#2780]
PhantomBot Version: Docker - 3.6.2.3
O/S Version: Linux Debian 9

Detailed Description:

when i update to 3.6.2.3 i keep getting 
"{"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}"

i rolled back to an older version as this doesnt happen on the older one i have used the allow_root true aswell to update to that version on the docker server.

Steps to Reproduce:

recreated the image and clicked run then the error appears straight away

Logs:

Screenshots (if applicable):

[Screenshot](https://ihostimages.uk/images/2022/04/28/msedge_Zce13whzGp.png)

**Comment by gmt2001** [comment]
You didn't `docker pull` the latest image. It is working fine in 3.6.2.3

![image](https://user-images.githubusercontent.com/3355471/165848281-2da9aa4b-3d84-46e9-8392-2db58637c19f.png)

**Comment by worldofmadness** [comment]
So i have checked and rechecked if I go above 3.6.0.1 i get lots of errors the image IS pulled for 3.6.2.3 i have confirmed this and downloaded previous versions as soon as i go above 3.6.0.1 it breaks and there is no reason why i can not find even looking through the errors

**Comment by gmt2001** [comment]
Need to know what the errors are

**Comment by worldofmadness** [comment]
3.6.0.1 - starts and runs fine

3.6.1 - The directory is not chown by the service user
Please run the following command to fix this:
   sudo docker exec --user root -it phantombot chown -R -H -L phantombot:phantombot /opt/PhantomBot
                                    ^
                                    Replace with the name of the container

3.6.2 - The directory is not chown by the service user
Please run the following command to fix this:
   sudo docker exec --user root -it phantombot chown -R -H -L phantombot:phantombot /opt/PhantomBot
                                    ^
                                    Replace with the name of the container

3.6.2.1 - {"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}
 
3.6.2.3 - {"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}
                                   
3.6.2.4 - {"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}

**Comment by gmt2001** [comment]
Try running `docker pull gmt2001/phantombot-stable:latest`

Then delete the container and create it again using `gmt2001/phantombot-stable:latest` as the image

**Comment by worldofmadness** [comment]
ok that worked had to rebuild the new container and seems to be all updated to 3.6.2.4 and so far its running no errors Thanks @gmt2001

**Comment by gmt2001** [comment]
Docker has this thing where, to prevent you from getting an unwanted update, it will not re-download the latest version of the image tag unless you completely delete it from the local Docker repository copy or use `docker pull` to force it

**Comment by gmt2001** [comment]
For the same reason, it will not change the copy of the image used on a particular container, even after a pull, unless the container is re-created
