### ISSUE TITLE
Greeting System greets twice

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2804]
PhantomBot Version: 3.6.2.6 (stable, Docker) (Revision: unknown)
Operating System: Linux
Java Version: 11.0.15+10
Web Browser Version (if Panel related): 1.6.3

Detailed Description:
The bot greets twice if a personalized greeting has been set. Once the user joins the channel (with the personalized greeting) and once the user writes in chat (with the generic greeting). It would be better to make this consistent, so that the bot only greets once summon has written in chat.

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by Sartharon** [comment]
Those are two different systems the greeting system and the welcome system you can turn them off separetly.
But might sound like a good idea to not welcome users which have a greeting set

**Comment by Alucard2112** [comment]
Wouldn't it be easier to simply overwrite the message if one is set?
So the systems behave the same :)

**Comment by Sartharon** [comment]
The systems are not connected in anyway
But i'm sure this counts as an enhancement and can be done with only a few lines of code adding a user toggleable option for this
