### ISSUE TITLE
Discord Alerts not Working

### ISSUE THREAD

**Issue by Highpurity** [PhantomBot/PhantomBot#2811]
PhantomBot Version: 3.6.2
O/S Version: Ubuntu
Java Version: 17
Web Browser Version (if Panel related): Not related

Detailed Description:

Discord integration doesn't post my clips in the channel I specified, same with all of the other discord integrations. Discord bot appears as online and responds to to other commands, just doesn't post alerts. The module is turned on and is fully configured.

Steps to Reproduce:

Setup phantombot as normal, same with discord integration. then, attempt to setup alerts. Not sure if this is user-specific, but I've tried running the bot on different vps's, different java versions, even reset the bot a couple times. No luck on fixing it.

Logs:

None applicable - doesn't show anything abt the discord bot.

Screenshots (if applicable):
N/A

**Comment by gmt2001** [comment]
Please perform the following tasks in order, to ensure everything has been configured properly

From the PhantomBot web panel:

- Expand _Discord_ and click _Alerts_
- Ensure the switch next to _Follower Alerts_ is toggled on (to the right, with purple shading)
![image](https://user-images.githubusercontent.com/3355471/171035149-3951ac10-04df-4774-a648-ab9a08516ef1.png)

- Click the settings cog next to _Follower Alerts_ and ensure the following settings:
  - _Enable Follow Alerts_: **Yes**
  - _Follow Message_: **Not empty**
  - _Alert Channel_: **Valid channel selected**
  - Click **Save**
![image](https://user-images.githubusercontent.com/3355471/171035314-bbb4889a-f089-4056-83a7-3092e84b18a9.png)

From Discord:

- Click your server name, then click _Server Settings_
- Click the _Roles_ tab
- Drag your bots role to the top of the list
- Click the pencil icon next to the bots role
- Click the _Permissions_ tab
- Ensure the bot has the _Administrator_ permission, or if you don't want to grant that permission, enable the following permissions instead:
  - _View Channels_
  - _Send Messages_
- Click the floating _Save Changes_ button

If you chose to not grant the _Administrator_ permission in Discord:

- Click the settings cog next to the target channel
  - Alternatively, you can do this on the entire category instead
- Click the _Permissions_ tab
- Click _Advanced Permissions_ to expand it
- Click the plus next to _Roles/Members_
- Click the role for your bot
- Ensure the role for your bot is now selected under _Roles/Members_
- Click the check mark next to _View Channel_
- Click the check mark next to _Send Messages_
- Click the floating _Save Changes_ button

From the bot console (when running via _launch.sh_):

- Wait a minimum of 2 minutes after starting the bot
- Run command _followertest_
- Check the selected Discord channel for the message

If all of these steps succeed, repeat the panel steps for other alert types. Also, if you chose to not grant the _Administrator_ permission in Discord, you may have to repeat the special permission steps for any additional channels which may be intended to receive alerts
