### ISSUE TITLE
Chatlimit not Working Correctly

### ISSUE THREAD

**Issue by oneandonlyjason** [PhantomBot/PhantomBot#2839]
PhantomBot Version: 3.6.2.5
O/S Version: Debian 11
Java Version: 11.0.14.1

Detailed Description:

I got the Error Message in the Console that the Chat Limit was reached and the Bot did wait a long time to send the Rest of the Messages. But the Log shows a (19) and there was not really much more messages that this. But since the Bot is a Moderator the Limit should be 100 Messages in 30 Seconds according to the Twitch Docs.

Steps to Reproduce:
Let the Bot send some Messages quickly

Logs:

[WARN] [onNext()@TwitchSession.java:210] Message limit of (19.0) has been reached. Messages will be sent again in 22933ms

**Comment by gmt2001** [comment]
The limit was set to 19 because people did dumb things in the past and complained. You can override the limit if you are 100% certain that you won't unmod, timeout, or ban the bot by adding the following on a new line in your botlogin.txt while the bot is shutdown 

```
msglimit30=100
```

**Comment by gmt2001** [comment]
I will keep this issue open since I will at some point look to refactor this to use auto detection as I believe Twitch has the proper facilities in place to detect status changes now
