### ISSUE TITLE
Failed to authorize and save the bot token: invalidJSONResponse{"message"_"invalid client secret","status":403}

### ISSUE THREAD

**Issue by mrquim** [PhantomBot/PhantomBot#2860]
PhantomBot Version: v3.6.3.4
O/S Version: Windows 11 x64
Java Version: 8 (Update 341)
Web Browser Version (if Panel related): I tried with Brave and Firefox

Detailed Description: After i insert Client ID here: and the Client Secret , i save it and then when i click on "Connect with Twitch Bot", authorize i get an error "Failed to authorize and save the bot token: invalidJSONResponse{"message"_"invalid client secret","status":403}". I tried to use the other button "Connect with Twitch Broadcaster" and i got the same error.

Steps to Reproduce: Click on "Connect with Twitch Bot" and authorize. Click on "Connect with Twitch Broadcaster" and authorize.

Screenshots (if applicable):

![PhantomBot__ERROR_403](https://user-images.githubusercontent.com/7824213/180584395-6ed9d2f6-a167-4b84-852d-913b0e11fe1f.jpg)

**Comment by gmt2001** [comment]
Please re-enter the Client ID, generate a new Client Secret, enter the new Client Secret, and click the Save button

You should see a green success message on the page indicating that they were saved. Then check your _botlogin.txt_ file, located in the config folder, to verify that you see both of those values correctly saved against the values that are on your Twitch Manage Application page

After that, give the Connect buttons another try

**Comment by mrquim** [comment]
This is what I did, before creating this thread, I tried it more than 10 times and the information in the botlogin.txt file is correct.

I'm not at home right now, but later when I get home I'll try to make everything from scratch (because this was an upgrade from the previous version to this newer one). And then I leave the feedback here.

**Comment by gmt2001** [comment]
It looks like I forgot to put in code to eliminate spaces at the beginning and end of the Client ID and Client Secret. Double check that there are no spaces, which can sometimes sneak in when you are highlighting something to copy it.

A tip to avoid the spaces is to double-click on the text to highlight it. I will add the fix for it to an upcoming nightly

**Comment by mrquim** [comment]
I check it and i dont have no spaces on beginning or at the end.

I tried to make a new installation from zero and the bot is working, with a few warns, but working.
![phantombot](https://user-images.githubusercontent.com/7824213/180628608-f8ed71c4-4444-42f6-8318-8dde4435b4d9.png)

**Comment by gmt2001** [comment]
The warning is because when you did the `Connect with Broadcaster` button you did not use the account that matches the actual channel the bot is connected to. I will put a fix in for the fact that it is spamming that. It isn't supposed to spam when that particular error occurs

**Comment by mrquim** [comment]
U right, i didnt use the broadcaster account on "Connect with Broadcaster". After the strugle, i have the bot full functional again. Thanks for your help man, i apreciate it very much.
