### ISSUE TITLE
Channel Points Predictions & Disable/Enable blacklist words by command

### ISSUE THREAD

**Issue by ghost** [PhantomBot/PhantomBot#2877]
Is there a way to enable/disable blacklist words with a command? Also will there be avaliable a command to start and pay channel points predtions and choose the winner?

**Comment by gmt2001** [comment]
The `!blacklist` command can be used to manage the blacklist from Twitch chat. The default permission level required to use it is _Administrator_

I can add Channel Point Predictions to the feature request queue, though it may be some time before I get to it

**Comment by ghost** [comment]
> The `!blacklist` command can be used to manage the blacklist from Twitch chat. The default permission level required to use it is _Administrator_
> 
> I can add Channel Point Predictions to the feature request queue, though it may be some time before I get to it

Yes, but you can only add words/remove? How can you disable/enable via a command?

**Comment by gmt2001** [comment]
If you mean enabling and disabling a blacklist word without actually adding/deleting it, we do not have that as a feature
