### ISSUE TITLE
Rank respond on Kill command

### ISSUE THREAD

**Issue by zpammer** [PhantomBot/PhantomBot#2881]
PhantomBot Version: 3.6.3.3-NB-07222022 (nightly_build) (Revision: https://github.com/PhantomBot/PhantomBot/commit/053fe41622f0d3322ac1f01c0576f39026110463)
O/S Version: Windows Server 2022 21H2
Java Version: windows build in 11.0.14.1+1
Web Browser Version (if Panel related): 1.6.5

Detailed Description
I never make use of the kill command. It is turned off normally.
But I don't think it picks up the correct ranks as mak-ke is far from somebody who has spend 0-2 hours in the chat.

![JKO60in3mC](https://user-images.githubusercontent.com/11378079/183267227-21d49c9b-062e-47a9-925d-1fd4a9f50d83.png)
![gZcaVe6iCN](https://user-images.githubusercontent.com/11378079/183267449-5766b894-ed6b-4e79-8122-05eab2b93201.png)
![WuoTcsKVGJ](https://user-images.githubusercontent.com/11378079/183267450-de4dd07c-d4d5-4fa8-b442-1dbbf8221f7a.png)
:

**Comment by zpammer** [comment]
Not functioning yet. It however looks like it does the same patern.
viewer vs regular, but both should be regular.

![image](https://user-images.githubusercontent.com/11378079/185697859-02396aab-6565-4089-8e43-37155a40a39c.png)

**Comment by gmt2001** [comment]
Try doing it without @tagging

**Comment by zpammer** [comment]
Correct rank responds in that case, but it is odd that when you make use of a mention the correct rank gets selected for the one you mention and the other is viewer-rank.

**Comment by gmt2001** [comment]
It isn't stripping the `@`
