### ISSUE TITLE
Support symbolic links

### ISSUE THREAD

**Issue by Barrikin** [PhantomBot/PhantomBot#2897]
https://github.com/PhantomBot/PhantomBot/blob/5e582098cc209a75df3bb02a8de1759f3c7790c7/javascript-source/init.js#L195

Would be better to use the following to support symbolic links.

$.getCanonicalFile().isDirectory('./scripts/' + path + '/' + files[i])

VS
$.isDirectory('./scripts/' + path + '/' + files[i])

**Comment by gmt2001** [comment]
Paths are already resolved to their real destinations

Symlinks are intentionally blocked if they go outside the intended folders for security, due to command tags allowing arbitrary paths to potentially be read into chat

**Comment by gmt2001** [comment]
If you are absolutely sure about what you are doing you can use a hardlink to bring in an external folder

**Comment by Barrikin** [comment]
> If you are absolutely sure about what you are doing you can use a hardlink to bring in an external folder

You can't really hard link a folder, and hard links in general are bad. What about a config var for the custom script folder?
