### ISSUE TITLE
Sound requests have wrong duration

### ISSUE THREAD

**Issue by Psychoboy** [PhantomBot/PhantomBot#2901]
PhantomBot Version: 3.6.4
O/S Version: Windows 11
Java Version: 11.0.14
Web Browser Version (if Panel related): Any

Detailed Description:
Song requests show/calculate incorrect duration now

Steps to Reproduce:
Add a song to song queue
Duration will be incorrect

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Can you please provide the YT URL and the duration that PB is reporting of an example song that was showing the wrong duration?

**Comment by Psychoboy** [comment]
https://youtu.be/SmbmeOgWsqE
Reports 00:46 when in reality is 2:45

https://youtu.be/GurkREc-q4I
reports 00:08 when in reality is 5:07

**Comment by Psychoboy** [comment]
To add to that for the 2nd one I posted above the API returns PT5M8S so pretty sure it's just grabbing the 8S and not the 5M

**Comment by gmt2001** [comment]
API is being parsed correctly. Found a stupid that someone did with the parsed result it over 7 years ago. Standby...
