### ISSUE TITLE
Using SSL Certificate assigned from Plesk

### ISSUE THREAD

**Issue by silez** [PhantomBot/PhantomBot#2905]
**PhantomBot Version:** v3.6.4.4 (Build Revision: 66965ce)

**O/S Version:** Debian GNU/Linux 10 (buster)

**Java Version:**
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode, sharing)

**Web Browser Version (if Panel related):**
Firefox: 103.0.2 (64-Bit)
Chrome: 104.0.5112.102 (Offizieller Build) (64-Bit)
Opera: But Opera is Chrome-Engine as we know :D

**Detailed Description:** 
I've been using a dedicated server for years. The Pleask Obsidian version is installed on this. I also use it to manage my IPs and of course the domains (and subdomains).
All (sub)domains are of course issued with a Let's Encrypt (free) certificate (via Plesk).

And here it comes:
I created a subdomain and uploaded the PhantomBot files accordingly.
How can I tell the PhantomBot that I'm already using an existing SSL/TLS certificate?
I have already read the instructions from https://phantombot.dev/guides/#guide=content/integrations/twitchembeds and tried to implement them. Since I use Plesk management, as mentioned, I can't use port 443, which is why PhantomBot doesn't start. Logical. I wouldn't like to use the remote panel either, since I have my own subdomain plus certificate.
Third point would be to set up a reverse proxy. Okay, next problem, Plesk manages all vhosts and if you make changes there, they are reset. You can use certain Apache or NGINX command extensions, but I don't know if that would be correct?!
Using the IP address, I can access the PhantomBot panel without any problems. However, if I now want to connect via the subdomain, the message appears which I have integrated here as "Screenshot 1". If I call up the domain directly with the port (as specified in the message), the browser tells me the certificate is not valid. Of course, the certificate I issued specifically for the domain is not used.

Maybe it's just a setting in the "botlogin.txt" that I forgot or was too stupid to read somewhere haha ​​but that's the current problem I have. Everything else works perfectly.

If you need more information, I will of course try to provide it. Thanks in advance for any tip you can give me.

**Steps to Reproduce:** 
As easy as explained above in the detailed text. Just use Plesk, create a subdomain, then create a free certificate via lets encrypt and bang the problem is there :)

Logs: 
There are no logs because the bot works smoothly via SSH console, only the call in the browser does not work because of the SSL/TLS certificate.

**Screenshots (if applicable):** 
Screenshot 1:
![Screenshot1](https://user-images.githubusercontent.com/8078098/185932807-fc2df667-020d-4fdb-8114-f5db0f072f0d.png)

Screenshot 2:
![Screenshot2](https://user-images.githubusercontent.com/8078098/185932814-8095a33e-60c1-443b-b7f2-8b23b9d6e856.png)

**Comment by gmt2001** [comment]
You can use Java's `keytool` to import the certificate to a .jks file, copy the jks to the bot folder, then set botlogin.txt to use that file instead and restart it. I am not sure how Plesk actually renews LetsEncrypt certificates, but if it uses CertBot then it's possible to drop a .sh script into the CertBot hooks folder to automate the jks update and bot restart on new certificate deploy

**Comment by silez** [comment]
@gmt2001
Hi and thanks for your answer :)
The tip was very good.
I tried this with the following command in the console:
`keytool -importcert -file Lets_Encrypt_twitchbot.xenokeks.eu.pem -keystore keystore.jks`
Since Plesk adds a part with `Begin Certificate Request` to the .pem, I just had to remove this part.
After that, the keytool no longer spit out an error.
Now, as you said, I have uploaded the jks to the folder and adjusted the botlogin.txt.
I added the following commands:
`usehttps=true`
`httpsFileName=/var/www/vhosts/xenokeks.eu/twitchbot.xenokeks.eu/config/keystore.jks`
`httpsPassword=PASSWORD`

The bot also starts flawlessly. However, when I try to call up the URL in the browser, the following error message appears:
`ERR_SSL_PROTOCOL_ERROR`

Have I done something wrong now?

Thank you in advance :)

**Comment by gmt2001** [comment]
Please check your `core-error` log for any SSL-related errors

**Comment by silez** [comment]
The last log error was
`[08-22-2022 @ 23:15:54.420 GMT] java.io.IOException: keystore password was incorrect`
but i fixed it with the line `httpsPassword=PASSWORD`
since that there was no errors anymore

**Comment by gmt2001** [comment]
Try this procedure, you will need the `openssl` package from apt for this

NOTE: This is based on the default paths, adjust as neccessary

1. Create a p12 with the entire certificate chain
```
openssl pkcs12 -export \
	 -in /etc/letsencrypt/live/twitchbot.xenokeks.eu/cert.pem \
	 -inkey /etc/letsencrypt/live/twitchbot.xenokeks.eu/privkey.pem \
	 -out /tmp/twitchbot.xenokeks.eu.p12 \
	 -name twitchbot.xenokeks.eu \
	 -CAfile /etc/letsencrypt/live/twitchbot.xenokeks.eu/fullchain.pem \
	 -caname "Let's Encrypt Authority X3" \
	 -password pass:changeit
```
Make sure you change the `changeit` to a reasonable password

2. Import the p12 into a jks
```
keytool -importkeystore \
	-deststorepass changeit2 \
	-deststoretype pkcs12 \
	-srckeystore /tmp/twitchbot.xenokeks.eu.p12 \
	-srcstoretype PKCS12 \
	-srcstorepass changeit \
	-destkeystore /tmp/twitchbot.xenokeks.eu.jks \
	-alias twitchbot.xenokeks.eu
```
Make sure you change the `changeit2` to a reasonable password
Make sure that `changeit` is set to the same value as in step 1

3. Shutdown the bot
4. Copy the jks to the phantombot folder
5. Verify that _httpsFileName_ in botlogin.txt points to the jks
6. Verify that _httpsPassword_ in botlogin.txt is the same as the password that replaced `changeit2` in step 2
7. Start the bot

**Comment by silez** [comment]
@gmt2001 
I've done it exactly like this.
Many thanks for the help!
Now everything works as it should. The login worked immediately and the certificate is also accepted directly.
Apparently I didn't specify enough parameters for the keystore command, i guess.
I will support the project as much as I can! Thanks again and stay the way you are :)
