### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by jjjonesjr33** [PhantomBot/PhantomBot#2958]
PhantomBot Version: Tested with versions 3.6.6.1, 3.6.6.2, and 3.6.6.3 all with the same issue.
O/S Version: Unraid / Docker
Java Version:
Web Browser Version (if Panel related):

Detailed Description:

Links in messages are not working/showing on twitch when using the bot. Does not matter if the bot has editor or mod. However it works when they are VIP ... but then it looses access to being a mod.

Steps to Reproduce:

Running a command that has a link programmed in it.

Logs:

Screenshots (if applicable):

![image](https://user-images.githubusercontent.com/29973406/198169096-161114fd-0254-4520-9710-3ba671fe4cac.png)

**Comment by gmt2001** [comment]
Can you show an example of an actual link that you tried?

**Comment by jjjonesjr33** [comment]
Yeah @gmt2001 for that test I used google.com and http://google.com

Today I did some more tests and this is what I'm seeing. When logged into the bot and posting the same message
```
/announce testing google.com
testing google.com
```
The only time I am able to get the links to show without an issue is disabling "Block Hyperlinks" but that defeates the purpose of someone being a mod and allowed to post a link.

![image](https://user-images.githubusercontent.com/29973406/198381829-dc87da58-02d5-469a-a326-4c3e0e1e831b.png)

Posting directly as the bot aka user I get this result
![image](https://user-images.githubusercontent.com/29973406/198380959-78faad1c-604c-4d4b-89d7-0e4645c15526.png)

When posting the message directly though PhantomBot the links are completely blocked
![image](https://user-images.githubusercontent.com/29973406/198380996-09a2126c-934c-4a78-9725-6bc28c1714da.png)

Once I turn "Block Hyperlinks" off it works without an issue

![image](https://user-images.githubusercontent.com/29973406/198382487-0f1a7840-d66e-4249-bc83-3d6b4cbc35da.png)

Example:
![image](https://user-images.githubusercontent.com/29973406/198382171-eff08ead-5c59-4a29-98e1-db25b99bf8b7.png)

Before these latest updates from 3.6.6.* this was working without an issue with "Block Hyperlinks" on, so that's where I'm at a loss atm.

**Comment by gmt2001** [comment]
I am not quite sure what is going on here. It appears to be a Twitch issue unfortunately. With the information you've given, it is not possible that the bot code is having any effect, but it is possible that Twitch is treating the bot account differently when you are using their website chat client as opposed to a third-party connection. It might be best to open a support ticket with Twitch about this behavior

**Comment by gmt2001** [comment]
Was apparently a Twitch issue
