### ISSUE TITLE
YouTube API broken

### ISSUE THREAD

**Issue by gnkidwell** [PhantomBot/PhantomBot#2998]
PhantomBot Version: 3.6.6.3
O/S Version: Ubuntu Server 20.04
Java Version: Not Sure
Web Browser Version (if Panel related):

Detailed Description: Phantombot 3.6.6.3 had a YouTube API change made, it no longer allows for searching of music by titles via !addsong 'title here'

**Comment by gnkidwell** [comment]
source/com/gmt2001/YouTubeAPIv3.java

Lots of lines were deleted between versions 3.6.5.2 and 3.6.6.3... Can we look at trying to remedy these? For now I am staying on 3.6.5.2...

**Comment by gmt2001** [comment]
This was fixed in nightly, it wasn't recognizing when the attempt to treat the search string as a video-id was failing so that it could fallback to using it as a title search, when using the new code

**Comment by gnkidwell** [comment]
> This was fixed in nightly, it wasn't recognizing when the attempt to treat the search string as a video-id was failing so that it could fallback to using it as a title search, when using the new code

Good to know, anyway to run the nightly until fixed?

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/nightly-build
