### ISSUE TITLE
Edit Channel Points Reward

### ISSUE THREAD

**Issue by AnonBit** [PhantomBot/PhantomBot#3015]
PhantomBot Version: 3.7.0.0 (stable) (Revision: 21a7f79)
O/S Version: Ubuntu 22.04.1 LTS
Java Version: 11.0.14.1+1
Web Browser Version (if Panel related):

Detailed Description:
Impossible to Edit Channel Points Reward button Save not work.
delaysay and delaycommand is posted immediately ignoring delay value

Steps to Reproduce:
Try to save modifications

Logs:
N/A

Screenshots (if applicable):

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/PhantomBot/blob/master/javascript-source/core/transformers/commands.js#L146

https://github.com/PhantomBot/PhantomBot/blob/master/javascript-source/core/transformers/basic.js#L99

`*1000`

**Comment by gmt2001** [comment]
https://github.com/PhantomBot/PhantomBot/blob/master/resources/web/panel/js/pages/loyalty/channelpoints.js#L233

`.val()`
