### ISSUE TITLE
updateCustomReward failing with certain edits / (cpcancel) not cancelling redemption

### ISSUE THREAD

**Issue by dexodarap** [PhantomBot/PhantomBot#3043]
PhantomBot Version: 3.7.1.2
O/S Version: Ubuntu 20.04.5 LTS
Java Version: Supplied from bot release
Web Browser Version (if Panel related): Safari 16.2

Detailed Description:
- Cannot make any edits to redeemables through the panel; nothing happens upon clicking save.
- Cannot update only the prompt with `$.helix.updateCustomReward`.
- Cannot disable `max_per_stream`, `max_per_user_per_stream` or `global_cooldown` limits with `$.helix.updateCustomReward` — i.e. once a limit is set through the bot, it can only be disabled through the Creator Dashboard.
- Cannot clear the prompt / set the prompt to be blank with `$.helix.updateCustomReward`.
- Using `(cpcancel)` tag in a bot reward does not cancel the redemption.

Steps to Reproduce:
1. Edit any field(s) of a managed redeemable through the panel, then click save.
2. Updating only the prompt with `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, new_prompt, null, null, null, null, null, null, null);` fails.
3. Updating `is_max_per_stream_enabled` with `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, bool, int, null, null, null, null, null);` only succeeds if `bool` is true.
4. Updating `is_max_per_user_per_stream_enabled` with `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, null, null, bool, int, null, null, null);` only succeeds if `bool` is true.
5. Updating `is_global_cooldown_enabled` with `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, null, null, null, null, bool, int, null);` only succeeds if `bool` is true.
6. Cannot update the prompt to be blank with `$.helix.updateCustomReward(redeemable_id, title, cost, is_enabled, is_paused, background_color, is_user_input_required, '', null, null, null, null, null, null, should_redemptions_skip_request_queue);`; the prompt remains as it was set previously.
7. Create a reward with response "`(cpcancel)`"; the reward does not get cancelled upon redemption.

Logs:
1) Editing redeemable through panel
```
[WARN] [handleRequest()@Helix.java:289] Helix rejected a request [/channel_points/custom_rewards?broadcaster_id=[REDACTED]&id=[REDACTED]] 400 Bad Request: The max_per_stream and is_max_per_stream_enabled fields are required if you specify either one of them.
[ERROR] [channelPointsHandler.js:480] Failed to Redeemable Update: HTTP 400: The max_per_stream and is_max_per_stream_enabled fields are required if you specify either one of them.
[ERROR] [init.js:408] Error with Event Handler [webPanelSocketUpdate] Script [./handlers/channelPointsHandler.js] Stacktrace [channelPointsHandler.js:481 > init.js:400 > init.js:810] Exception [TypeError: Cannot call method "toString" of undefined]
```

2) `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, 'test', null, null, null, null, null, null, null);`
```
[ERROR] [init.js:385] Error with Event Handler [command] Script [./custom/[REDACTED].js] Stacktrace [[REDACTED].js:324 > init.js:377 > init.js:656] Exception [JavaException: java.lang.IllegalArgumentException: Must specify at least 1 parameter to update]
Sending stack trace to error log...
[ERROR] [invoke0()@null:-2] java.lang.IllegalArgumentException: Must specify at least 1 parameter to update
```

3) `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, false, 1, null, null, null, null, null);`
```
[WARN] [handleRequest()@Helix.java:289] Helix rejected a request [/channel_points/custom_rewards?broadcaster_id=[REDACTED]&id=[REDACTED]] 400 Bad Request: The max_per_stream and is_max_per_stream_enabled fields are required if you specify either one of them.
```

4) `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, null, null, false, 1, null, null, null);`
```
[WARN] [handleRequest()@Helix.java:289] Helix rejected a request [/channel_points/custom_rewards?broadcaster_id=[REDACTED]&id=[REDACTED]] 400 Bad Request: The max_per_user_per_stream and is_max_per_user_per_stream_enabled fields are required if you specify either one of them.
```

5) `$.helix.updateCustomReward(redeemable_id, null, null, null, null, null, null, null, null, null, null, null, false, 60, null);`
```
[WARN] [handleRequest()@Helix.java:289] Helix rejected a request [/channel_points/custom_rewards?broadcaster_id=[REDACTED]&id=[REDACTED]] 400 Bad Request: The global_cooldown_seconds and is_global_cooldown_enabled fields are required if you specify either one of them.
```

6) `$.helix.updateCustomReward(redeemable_id, title, cost, is_enabled, is_paused, background_color, is_user_input_required, '', null, null, null, null, null, null, should_redemptions_skip_request_queue);`

Couldn't find anything in the debug logs for this, but all other updates to the redeemable succeed (except for the prompt).

7) `(cpcancel)`
```
[WARN] [handleRequest()@Helix.java:289] Helix rejected a request [/channel_points/custom_rewards/redemptions?broadcaster_id=[REDACTED]&id=[REDACTED]&reward_id=[REDACTED]] 400 Bad Request: The parameter "status" was malformed: value must be one of "CANCELED", "FULFILLED"
[ERROR] [channelPointsHandler.js:308] Failed to set Redemption Cancelled ([REDACTED], [REDACTED]): HTTP 400: The parameter "status" was malformed: value must be one of "CANCELED", "FULFILLED"
```

**Comment by gmt2001** [comment]
Leave it to Twitch to literally not say anywhere in the documentation that the is_enabled flags always have to be sent when updating the values

**Comment by gmt2001** [comment]
In test cases 3, 4, and 5 you are technically trying to tell it to turn those options OFF while at the same time trying to change their values, which should be an illegal operation. Try sending just `false` with a `null` value to disable, or `true` with a valid value to update the value

If you can get me the results of that, it would help as I fix the way the bot sends it

**Comment by gmt2001** [comment]
There is a known bug on Twitch's side where a blank prompt `''` does not work from the API

**Comment by gmt2001** [comment]
A new nightly will be available in approx 20 minutes. Try this all again with that version. The only thing that should fail, hopefully, is setting prompt to blank `''`

**Comment by dexodarap** [comment]
Thank you very much! 😊

The new nightly build appears to resolve all of these issues, except the blank prompt issue as you specified. Hopefully Twitch fix that soon!

Best wishes,
dexodarap
