### ISSUE TITLE
[ERROR] [followHandler.js:59]

### ISSUE THREAD

**Issue by emahiser** [PhantomBot/PhantomBot#3178]
PhantomBot Version: Latest
O/S Version: Windows 10
Java Version:
Web Browser Version (if Panel related):

Detailed Description: PhantomBot has been BROKEN since v3.8.0.  Been giving [ERROR] [followHandler.js:59].  v3.7.4.2 WORKS GREAT No Errors at all.

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Likely you did not reauthorize the API/Broadcaster token after updating. Twitch requires a new scope for follower tracking

The full error message in the `logs/error` log will confirm

**Comment by emahiser** [comment]
> Likely you did not reauthorize the API/Broadcaster token after updating. Twitch requires a new scope for follower tracking
> 
> The full error message in the `logs/error` log will confirm

That was it!  Must of not read if you explained that...  GERAT Bot and Keep up the good work!
