### ISSUE TITLE
phantombot redirection to localhost

### ISSUE THREAD

**Issue by traskat** [PhantomBot/PhantomBot#3191]
PhantomBot Version: 3.8.1.1
O/S Version: ubuntu focal
Java Version: docker-compose version from repo tag 3.8.1
Web Browser Version (if Panel related): firefox  version 111.0.1

Detailed Description:
if i start the bot via the docker-compose file from the repo. i set these variables:
```
PHANTOMBOT_PROXYBYPASSHTTPS: true
PHANTOMBOT_USEHTTPS: false
```
because i have an nginx in front of phantombot. is there an option get rid of the redirect to localhost. because no matter what i click on the phantom panel after starting the bot i always get redirect to localhost:25000
example:
https://my.domain.com/panel/login
https://localhost/panel/login

Steps to Reproduce:
NA

Logs:
NA

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Add
```
PHANTOMBOT_ENVOVERRIDE: true
```
to force your ENV variables to override the config

**Comment by traskat** [comment]
That worked so far.
thanks
