### ISSUE TITLE
cannot login with newly setup bot 

### ISSUE THREAD

**Issue by traskat** [PhantomBot/PhantomBot#3222]
PhantomBot Version: latest
O/S Version: docker latest tag
Java Version: version in container
Web Browser Version (if Panel related): firefox 112.0.2

Detailed Description:
after i do a docker compose up -d. i cannot login with the password i set in the compose yml. neither can i login with the given username and password after the bot setup.
iThe error i get in the dev console is a http 400 bad request.

i only have set these configurations:
```
PHANTOMBOT_PROXYBYPASSHTTPS: false
PHANTOMBOT_USEHTTPS: false
PHANTOMBOT_CHANNEL: noshog
PHANTOMBOT_ENVOVERRIDE: true
PHANTOMBOT_DEBUGON: true
PHANTOMBOT_INTERNALDEBUG: true
PHANTOMBOT_PANELUSER: user
PHANTOMBOT_PANELPASSWORD: password

```
Steps to Reproduce:

Logs:
the log for a login via token or the credentials i have set is just this:
```
 May 11, 2023 7:34:22 AM io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker handshake
phantombot  | FINE: [id: 0xa77634f1, L:/172.21.0.2:25000 - R:/172.21.0.1:36704] WebSocket version V13 server handshake
```

Screenshots (if applicable):

**Comment by gmt2001** [comment]
Recommend testing if the same error occurs in Chrome or Edge

**Comment by C74K** [comment]
cant login too
websocket dont work

**Comment by Locxion** [comment]
I can confirm this
`WebSocket connection to 'wss://myboturl/ws/panel/login?target=myboturl:443' failed: 
window.WebSocket @ pace.min.js:2
`
Tested with Chrome and Microsoft Edge
Phantombot Version 3.8.3.5 for Linux fresh install

**Comment by gmt2001** [comment]
Is your bot reverse proxied behind nginx?

If yes, please verify that you have the section
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
```
As well as the location directives
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```
As described in the nginx reverse proxy example
https://phantombot.dev/guides/#guide=content-stable/integrations/twitchembeds&channel=stable&jumpto=enable-twitch-embeds_method-3-setup-a-reverse-proxy_nginx-sample-config

**Comment by Locxion** [comment]
I run a Plesk Instance with various subdomains
Ive only updated to 3.8.3.5 recently and never had to use the "map" section til now.
In the Subdomain additional nginx directives i have 
```
location ~ / {
	proxy_pass         http://localhost:20069;
	proxy_http_version 1.1;
	proxy_set_header   Upgrade $http_upgrade;
	proxy_set_header   Connection keep-alive;
	proxy_set_header   Host $host;
	proxy_cache_bypass $http_upgrade;
	proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header   X-Forwarded-Proto $scheme;
}
```

i tried to add 
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
```
but it says that 

`nginx: [emerg] "map" directive is not allowed here in 1 nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by gmt2001** [comment]
The map directive needs to be a global directive, not in a subdomain. I don't know why nginx started acting this way with newer releases, but for some reason it stops forwarding the extra HTTP headers required for websockets to start
