### ISSUE TITLE
Bot still uses abandoned /w Command for Whisper Mode

### ISSUE THREAD

**Issue by Locxion** [PhantomBot/PhantomBot#3257]
PhantomBot Version: 3.8.3.5

Detailed Description:
Bot still uses /w Chat command for Whisper Mode.
This is abandoned by Twitch. Whispers only work directly via Twitch Helix Api.
https://dev.twitch.tv/docs/api/reference/#send-whisper

Steps to Reproduce:
Setup fresh Bot
Enable Whisper Module/Mode
Let the bot send a Whisper (for example with the Points Module)
Whisper gets send via /w in the Console but never reaches the targeted User.

Logs:

`
[06-01-2023 @ 12:38:11.128 GMT] locxion: !points
[06-01-2023 @ 12:38:11.224 GMT] [CHAT] /w locxion du hast momentan 4742467 Berry's und warst im Chat für 30930 Stunden und 54 Minuten.
`

**Comment by gmt2001** [comment]
The bot is programmed to catch this command and attempt to redirect it via the API, though Twitch limitations on sending Whispers via API may be blocking it. Please check the core-error and core-warning logs for any error that potentially indicates why it was blocked.

The general requirements given by Twitch is that the bot must have a verified phone number. There are also special rate-limits on number of users whispered per day and number of messages sent

Twitch may also use AI to detect potential spam and drop it silently while indicating success to the bot

You can also attempt to monitor the whisper send request in the console and debug logs by enabling `debugon` and `helixdebug` in the **Debug** section of the _Bot Settings_ page of your bots webserver (move the dot to the right to enable the switch, then toggle the switch on), saving, and then having it try again. A returned status code of **204** indicates success or silently dropping

API Reference
https://dev.twitch.tv/docs/api/reference/#send-whisper

**Comment by Locxion** [comment]
> The bot is programmed to catch this command and attempt to redirect it via the API, though Twitch limitations on sending Whispers via API may be blocking it. Please check the core-error and core-warning logs for any error that potentially indicates why it was blocked.
> 
> The general requirements given by Twitch is that the bot must have a verified phone number. There are also special rate-limits on number of users whispered per day and number of messages sent
> 
> Twitch may also use AI to detect potential spam and drop it silently while indicating success to the bot
> 

Account is registered on Twitch as Bot Account and has no msg blocking or limitations.
Account was tested with different Bot Software and via Postman.

> You can also attempt to monitor the whisper send request in the console and debug logs by enabling `debugon` and `helixdebug` in the **Debug** section of the _Bot Settings_ page of your bots webserver (move the dot to the right to enable the switch, then toggle the switch on), saving, and then having it try again. A returned status code of **204** indicates success or silently dropping

Will toggle this Debug options and post an update after further Tests
