### ISSUE TITLE
Panel Users: Users with Full Access do not have "Restart" option in Tools sidebar

### ISSUE THREAD

**Issue by fouram** [PhantomBot/PhantomBot#3304]
PhantomBot Version: 3.9.0.2
O/S Version: Docker/ubuntu
Java Version: Included
Web Browser Version (if Panel related): Firefox 115.0.1

Detailed Description:
In the description for #3227 it is stated that users with "Full Access" will have the Restart button for the bot available in their sidebar, but on creating new users and logging in, this control is not available.

Steps to Reproduce:
Create a new user, check the "Full Access" checkbox to assign all 18 permissions on creation. Log in as new user, set pw, etc and then once fully logged in, inspect sidebar

Logs: Not sure if this would be applicable. Please let me know if you need to me capture something

Screenshots (if applicable):

![Missing "Restart" button from Tools sidebar](https://github.com/PhantomBot/PhantomBot/assets/533951/367bcc5b-6755-47d8-a5a9-8356d6d56632)

**Comment by Sartharon** [comment]
The restart function has not been exposed due to the possible nature of disturbing a stream by constant restarts.

Though we can consider turning it back on for them

The PR you are refering to was the inital (basic) permissions. The actual PR implementing the full permission system currently available is #3258 https://github.com/PhantomBot/PhantomBot/pull/3258

**Comment by fouram** [comment]
> The PR you are refering to was the inital (basic) permissions. The actual PR implementing the full permission system currently available is #3258

Ah, ok I was looking at the wrong PR then. I do see where it says that this was changed:

> Only the bot owner can restart the bot via the panel (this can easily be changed to allow this for users with Full Access to the dashboard section)

It would be nice to either allow Full Access users, or add an additional permission for the Restart functionality. We have a very "hands off" broadcaster when it comes to bots (read: not super technically inclined), and so if the bot loses connection it's up to one of the mods to give it a kick. (This has been MUCH less of a problem as we get further from the Twitch API change, so props to the PB team for that!) Presently, as our instance is selfhosted, that would be me or the one other moderator who has the owner password. It's great that we can now give the other mods access to the features we want, but we would definitely trust more of our team with restart responsibility if we could delegate it.
