### ISSUE TITLE
Firefox can't display the embedded Twitch panels in the Dashboard due to security concerns

### ISSUE THREAD

**Issue by tkohnyo** [PhantomBot/PhantomBot#3308]
PhantomBot Version: 3.9.0.3
O/S Version: Windows 10 x64 21H2
Java Version: 17.0.7
Web Browser Version (if Panel related): Firefox 115.0.2 x64

Detailed Description:
The twitch panels at the main dashboard can't be displayed due to "security concerns" from firefox.

Steps to Reproduce:
Login and navigate to the dashboard

Logs:
None needed as it's not an exception or crash.

Screenshots (if applicable):
![Capture](https://github.com/PhantomBot/PhantomBot/assets/38466788/9dc7f598-9ad0-44c6-8ccd-89db8fc6871d)

**Comment by tkohnyo** [comment]
The "Learn More..." leads to the mozilla website:
https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct

**Comment by gmt2001** [comment]
Please verify that you are using SSL (`https` URL) on port 443 with a real domain name (free domain names such as noip are valid for this, as long as the SSL certificate matches)

**Comment by tkohnyo** [comment]
I used the https://phantombot.dev/panel-stable/login/ route to login into my localhost instance
![Capture_2](https://github.com/PhantomBot/PhantomBot/assets/38466788/06a7cfa4-0439-4b86-a2b7-55565ad4f769)

**Comment by gmt2001** [comment]
Try visiting Twitch's website directly in Firefox and re-logging in to your account, then refreshing the PhantomBot panel

**Comment by tkohnyo** [comment]
Ok Thank you, that did it for me. Was that some sort of oauth cookie issue?

**Comment by gmt2001** [comment]
Possible security precaution since it thought your login session to Twitch had expired
