### ISSUE TITLE
Migration from 3.9.0.3: Invalid datastore using SQLiteStore2

### ISSUE THREAD

**Issue by tkohnyo** [PhantomBot/PhantomBot#3312]
PhantomBot Version: 3.9.0.4
O/S Version: Windows 10 21H2 x64
Java Version: 17.0.7 x64
Web Browser Version (if Panel related):

Detailed Description:
After migrating the config files from the previous 3.9.0.3, it didn't launch anymore. Reason: Invalid datastore selected. PhantomBot now shutting down...
The previous bot on 3.9.0.3 ran with datastore=SQLiteStore2, so this should not be the issue as suggested by the changelog.
Maybe the local db needs to be migrated to a newer version though: "The update of mysql-connector 5.1.49 -> 8.0.33 may cause compatibility issues with MySQL Server versions older than 5.7" 

Steps to Reproduce:
Download version 3.9.0.4 and unzip
Copy config folder from 3.9.0.3
Launch it

Logs:
[logs.zip](https://github.com/PhantomBot/PhantomBot/files/12064099/logs.zip)

Screenshots (if applicable):
![image](https://github.com/PhantomBot/PhantomBot/assets/38466788/7c5a3a0b-b26c-47d7-8969-8d6d1045bdb1)

**Comment by gmt2001** [comment]
Release is rebuilding. Should be fixed after rebuild completes. Give it about 10-15 minutes

**Comment by tkohnyo** [comment]
Thank you for the quick fix!
