### ISSUE TITLE
Phantombot Docker-Version not working since .10 update

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#3358]
PhantomBot Version: 3.10.0.1
O/S Version: Docker (Linux)
Java Version: 17
Web Browser Version (if Panel related):

Detailed Description:
Phantombot will not start. Worked with 3.9.0.7. Downgrading the Docker-Image still works fine.
"/opt/PhantomBot/launch-docker.sh: line 64: --add-exports: command not found" seems to be the issue

Steps to Reproduce:
Launch Phantombot via docker

Logs:

phantombot_morelle | --2023-08-26 09:44:35--  https://raw.githubusercontent.com/PhantomBot/PhantomBot/master/resources/config/healthcheck/healthcheck.py
phantombot_morelle | Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
phantombot_morelle | Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
phantombot_morelle | HTTP request sent, awaiting response... 200 OK
phantombot_morelle | Length: 10859 (11K) [text/plain]
phantombot_morelle | Saving to: ‘/opt/PhantomBot/config/healthcheck/healthcheck.py’
phantombot_morelle |
/opt/PhantomBot/con 100%[===================>]  10.60K  --.-KB/s    in 0s
phantombot_morelle |
phantombot_morelle | 2023-08-26 09:44:36 (46.8 MB/s) - ‘/opt/PhantomBot/config/healthcheck/healthcheck.py’ saved [10859/10859]
phantombot_morelle |
phantombot_morelle | --2023-08-26 09:44:36--  https://raw.githubusercontent.com/PhantomBot/PhantomBot/master/resources/config/healthcheck/healthcheck.py
phantombot_morelle | Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
phantombot_morelle | Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
phantombot_morelle | HTTP request sent, awaiting response... 200 OK
phantombot_morelle | Length: 10859 (11K) [text/plain]
phantombot_morelle | Saving to: ‘/opt/PhantomBot/config/healthcheck/healthcheck.py’
phantombot_morelle |
/opt/PhantomBot/con 100%[===================>]  10.60K  --.-KB/s    in 0s
phantombot_morelle |
phantombot_morelle | 2023-08-26 09:44:36 (50.8 MB/s) - ‘/opt/PhantomBot/config/healthcheck/healthcheck.py’ saved [10859/10859]
phantombot_morelle |
phantombot_morelle | /opt/PhantomBot/launch-docker.sh: line 64: --add-exports: command not found

Screenshots (if applicable):

**Comment by gmt2001** [comment]
I am not able to reproduce this on my system. Can you provide your OS, Processor Type, and whether you are using Docker Hub or GitHub Packages so I can check further?

**Comment by Alucard2112** [comment]
I am using ghcr.io/phantombot/phantombot, so that should be the github one, right? :)

Linux v22019071079493953 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux

With the following parts:
-ADAE-407DBB9AFDE6
  *-core
       description: Motherboard
       physical id: 0
     *-firmware
          description: BIOS
          vendor: netcup
          physical id: 0
          version: VPS 1000 G8
          date: 07/26/2019
          size: 96KiB
          capabilities: virtualmachine
     *-cpu
          description: CPU
          product: QEMU Virtual CPU version 2.5+
          vendor: Intel Corp.
          physical id: 400
          bus info: cpu@0
          version: pc-i440fx-4.2
          slot: CPU 0
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp de pse tsc msr pae mce cx8 apic sep                                                                                                                                                              mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 ht syscall nx x86-64 rep_good                                                                                                                                                              nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2                                                                                                                                                              x2apic popcnt aes xsave rdrand hypervisor lahf_lm cpuid_fault invpcid_single pt                                                                                                                                                             i ssbd ibrs ibpb invpcid md_clear
          configuration: cores=4 enabledcores=4 threads=1
     *-memory
          description: System Memory
          physical id: 1000
          size: 8GiB
          capabilities: ecc
          configuration: errordetection=multi-bit-ecc
        *-bank
             description: DIMM RAM
             vendor: QEMU
             physical id: 0
             slot: DIMM 0
             size: 8GiB

**Comment by gmt2001** [comment]
Try using the nightly build `ghcr.io/phantombot/nightly-build` and see if the updated launcher script fixes it

**Comment by Alucard2112** [comment]
Now I am getting
phantombot_morelle | /opt/PhantomBot/launch-docker.sh: line 73: ./java-runtime-linux/bin/java: No such file or directory
phantombot_morelle | /opt/PhantomBot/launch-docker.sh: line 83: ./java-runtime-arm64/bin/java: No such file or directory
phantombot_morelle | /opt/PhantomBot/launch-docker.sh: line 94: --version: command not found
phantombot_morelle | PhantomBot requires Java 17 to run
phantombot_morelle |
phantombot_morelle | Is your Docker image base set to eclipse-temurin:17-jre?

Do I have to change any values in the botlogin.txt?

**Comment by gmt2001** [comment]
Something appears to be not functioning properly in your Docker container as I am still unable to reproduce this

Try creating a new PhantomBot container from scratch and see if it launches properly
` docker run --name pb-test --pull always ghcr.io/phantombot/phantombot`

If that works, try backing up your persistent volumes and re-creating the production containers from scratch

You should perform the steps in this order
1. Backup persistent volume data for all PhantomBot containers
2. Remove all PhantomBot containers
3. Prune the image cache with `docker image prune`
4. Re-create the PhantomBot containers

**Comment by Alucard2112** [comment]
I am really sorry to trouble you again but I still get the same error:
phantombot_morelle | PhantomBot requires Java 17 to run
phantombot_morelle |
phantombot_morelle | Is your Docker image base set to eclipse-temurin:17-jre?

I can share my docker-compose, if that helps:

version: '3.3'
services:
  phantombot:
    container_name: phantombot
    image: ghcr.io/phantombot/phantombot:latest
    restart: always
    expose:
      - 25000
      - 25001
      - 25002
    labels:
      - traefik.enable=true
      - traefik.http.routers.phantombot.rule=Host(`mydomain`)
      - traefik.docker.network=web
    healthcheck:
      disable: true
    volumes:
      - ./botlogin.txt:/opt/PhantomBot_data/config/botlogin.txt:rw
      - ./phantombot.db:/opt/PhantomBot_data/config/phantombot.db:rw
      - ./custom_scripts/custom/:/opt/PhantomBot_data/scripts/custom/
      - ./custom_scripts/games/:/opt/PhantomBot_data/scripts/games/
      - ./custom_scripts/lang/:/opt/PhantomBot_data/scripts/lang/
      - ./logs/:/opt/PhantomBot_data/logs/:rw
    tty: true
    networks:
      - web

**Comment by gmt2001** [comment]
What is the output of `docker run --rm eclipse-temurin:17-jre /opt/java/openjdk/bin/java --version` ?

**Comment by Alucard2112** [comment]
Unable to find image 'eclipse-temurin:17-jre' locally
17-jre: Pulling from library/eclipse-temurin
99de9192b4af: Already exists
c5980221a1ce: Already exists
b561fbe0ad19: Already exists
afff93b71681: Already exists
203befd68707: Already exists
Digest: sha256:9eda8bc2e2e3d1dadab6ab1b5c698df0845db36cb95ad3b19ad37d4f25033bfa
Status: Downloaded newer image for eclipse-temurin:17-jre
[0.009s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_crea                                                                                                                                                             te failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# //hs_err_pid1.log

It seems like a memory issue oO
I have to confess that I do not know why this would happen. The older version runs without a problem oO

**Comment by gmt2001** [comment]
What is the current version of Docker? `docker --version`

**Comment by Alucard2112** [comment]
Docker version 18.09.1, build 4c52b90

**Comment by gmt2001** [comment]
Based on that error message when you tried to check the Java version, there is a security profile compatibility issue caused by the newer version of Ubuntu used as the base for the Docker image

It can be fixed by either updating Docker to 20.10.10 (or later), or by modifying the docker-compose to bypass the security setting

If you want to modify the docker-compose file, add the following to the `phantombot` service section

```
  security_opt:
    - seccomp:unconfined
```

**Comment by Alucard2112** [comment]
Thank you! Updating to a later docker-version did the trick. Unsure why debian did not do so by itself but problem solved :)

**Comment by MentalFS** [comment]
You Kernel and Docker versions look like you might be running Debian Buster (old-old-stable):
https://packages.debian.org/search?keywords=docker.io
https://packages.debian.org/source/buster/linux

Maybe it's time to upgrade the system.
