### ISSUE TITLE
Add the ability to use commands in User Greetings messages

### ISSUE THREAD

**Issue by Buhster** [PhantomBot/PhantomBot#3378]
PhantomBot Version: 3.10.0.3 Build Revision: 6d62f9b
O/S Version: Windows 11 22h2 (build 22621.2134)
Java Version: 17.0.8.1
Web Browser Version (if Panel related): 

Detailed Description:
As far as I understand, there is no way to use commands in messages now. I'd like to diversify greetings with things like readfilerand or sound effects (for example, so I know when my favorite moderator comes into the chat).

Steps to Reproduce:
I try to use something like `/me (name) HeyGuys (command readfilerand Chatbot/top.txt)` but bot send message like _SomeUserName HeyGuys (readfilerand Chatbot/top.txt)_

Logs:
no log at all

Screenshots (if applicable):

**Comment by BrandenB** [comment]
Added in #3423
