### ISSUE TITLE
Quote mode format toggle regression

### ISSUE THREAD

**Issue by ddugovic** [PhantomBot/PhantomBot#3442]
PhantomBot Version: latest
O/S Version: Ubuntu latest
Java Version: latest
Web Browser Version (if Panel related):

Detailed Description:
I'd like to be able to display quotes (classical shogi proverbs) without them being attributed to me.  Command !quotemodetoggle doesn't seem to do anything, and I can't find the config. file to toggle the setting myself.

Steps to Reproduce:
!addquote toadofBigsby 王手は追う手 - To check is to chase (lit. A check is a chasing move)
!quote
!quotemodetoggle
!quote

Logs:
![image](https://github.com/PhantomBot/PhantomBot/assets/1834123/46db8564-f35d-4e00-820d-036299de1838)
![image](https://github.com/PhantomBot/PhantomBot/assets/1834123/676ca9f2-3bd0-472c-9837-de170bab8bb3)

**Comment by ddugovic** [comment]
I'll reconfigure PhantomBot to use FrogfuciusBot instead of impersonating me, but I don't think that's the cause of this issue.

**Comment by BrandenB** [comment]
Responded here: https://discord.com/channels/107910097937682432/1172594783798186056

**Comment by ddugovic** [comment]
Many thanks! I now understand usage:
- `!quotemodetoggle` toggles usage for adding new quotes (and prints the updated usage command)
- `!quotemessage` sets the format string (for example `!quotemessage toadofBigsby (quote)` hides the user, date, etc. and also prefixes each quote with my channel follower emote)
