### ISSUE TITLE
Addition of YouTube chat moderation/functionality?

### ISSUE THREAD

**Issue by GuardEzio** [PhantomBot/PhantomBot#3473]
Hail! Sorry if it's the wrong place; I couldn't find any other contact and no info in the documentation other than the instructions to link for YouTube API (which looks only to add some minor YouTube functionality). 

With the changes to Twitch allowing for multicasting, is there any possibility or plans for functionality to be added to PhantomBot to allow for moderation & custom commands across both Twitch and YouTube streams? 

Many Regards, 
Ezio

**Comment by gmt2001** [comment]
Sorry, we are not planning to support this right now because our core and scripts are tightly integrated with Twitch as the streaming platform and we are not looking to do a major rewrite of the scale required at this time
