### ISSUE TITLE
Bot won't start on Windows 11 Pro

### ISSUE THREAD

**Issue by Cupara** [PhantomBot/PhantomBot#3474]
PhantomBot Version: 3.11.0.3
O/S Version: Windows 11 Pro 22H2 (Build: 22621.2861)
Java Version: JDK 17
Web Browser Version (if Panel related): Chrome Version 120.0.6099.130 (Official Build) (64-bit)

Detailed Description:
I am following the guide to getting started and I'm stuck at the double-click launch.bat. When I double-click it, a terminal window opens for about a second then closes. Nothing else happens. I have even tried running it as administrator but same thing.

Steps to Reproduce:
1. Download latest Windows version.
2. Extract to C:\Program Files
3. Open newly created folder.
4. Double-click launch.bat

Logs:
No logs

Screenshots (if applicable):
None applicable

**Comment by Mythotical** [comment]
I figured it out. You can't place it in C:\Program Files. I placed the folder on my Desktop and it is working fine now.

**Comment by Cupara** [comment]
I figured it out. You can't place it in C:\Program Files. I placed the folder on my Desktop and it is working fine now.
