### ISSUE TITLE
Raid as Mod Issue

### ISSUE THREAD

**Issue by nieisi** [PhantomBot/PhantomBot#3494]
PhantomBot Version: PhantomBot Version: 3.12.1.0 (stable) (Revision: 4b6a0ad)
O/S Version: Linux (ubuntu 22.04 LTS)
Java Version: 17.0.8.1+1

Detailed Description:

if a raid comes from another channel, no more messages are sent to the chat. 
A few versions ago this worked perfectly and is now broken. I don't know if it ended up in the broadcaster verification, but it would be nice if you could take a look at it. I run the bot as a separate user with moderation rights. I can't connect the broadcaster, for various reasons that have nothing to do with the phantombot settings.

But I have to say, it's a mega cool project.

**Comment by gmt2001** [comment]
Are you able to provide any logs from the bot console around the time when the raid came in and you subsequently tried to use a command? I am unable to reproduce this on my side and need to figure out why yours is acting different

**Comment by nieisi** [comment]
I will have to wait for the next raid as I had no logs active in the bot settings. Or is there another log that runs permanently?
The command .shoutout (user) should be triggered during a raid.
Then I must first set my request to pending.

**Comment by nieisi** [comment]
I have now got a raid, but I can't find any logs that might be useful. 
Can you tell me exactly which logs you need? Otherwise it can be quite a lot.

**Comment by gmt2001** [comment]
core-error, core-warnings, js-error, and stacktraces from around the time of the raid (if they exist)

Also to clarify, the issue is that the `.shoutout (user)` is not working?

**Comment by nieisi** [comment]
Yeah the command .shoutout (user) don't work, I hope it is spelled correctly.
![image](https://github.com/PhantomBot/PhantomBot/assets/114303482/da60848a-33c8-498d-a3d1-ef181fffa753)

The raid was at 22:22, but due to the time difference it should appear in the logs around 21:22. I have not yet been able to enter the CET value correctly.

I can only upload a ZIP, so I just uploaded all the logs from that day.

There was also a time when I started the bot twice, which is also visible, but then I completely restarted the server once and then started a simple instance.

[log.zip](https://github.com/PhantomBot/PhantomBot/files/14426692/log.zip)

**Comment by gmt2001** [comment]
Try verifying that the module hasn't somehow disabled itself with `!module status ./handlers/raidHandler.js`

Also, try re-authorizing the "Broadcaster" token. Using the moderator bot account for this should be acceptable

**Comment by nieisi** [comment]
![image](https://github.com/PhantomBot/PhantomBot/assets/114303482/0cb0efd8-979c-4f6f-8220-112ff5790ca1)
I have already verified the bot again and carried out the authentication. But i do this again.
It shows this when you enter the command.

**Comment by nieisi** [comment]
![image](https://github.com/PhantomBot/PhantomBot/assets/114303482/a6af8b3b-b06c-4d76-af6c-f89a9fef6772)
my brain legs

I still have the debug mode activated and will summarize all the data I get.

**Comment by gmt2001** [comment]
Okay, lets try this

1. Shutdown the bot
2. Open `config/botlogin.txt`
3. Add/edit lines to enable debugging
```
debugon=true
helixdebug=true
```
4. Start the bot
5. Get another raid and then provide the core-debug log

**Comment by nieisi** [comment]
Thanks for your hint, I have attached the logs. The raid started at about 1:46 CET so according to the logs 0:46 GMT. 
I just remembered that I create an application via the Twitch developer console, but as far as I know, it has no moderator authorization. Could this perhaps be a mistake on my part?

**Comment by gmt2001** [comment]
As long as the account which actually performed the authorization is a moderator, it should work

Could you replace PhantomBot.jar with the latest nightly version and try one more time. Check the core-error logs to see if anything comes up. I added an extra error check to make sure we weren't missing anything. It looks like it is trying to send the shoutout but that there is a silent failure somewhere between processing the `.shoutout` command and actually submitting it to the API

https://github.com/PhantomBot/nightly-build

**Comment by nieisi** [comment]
I installed and started the nightly and then there was no raid for a while. Today, as if enchanted, a raid and the message appeared. I haven't changed anything since then or made an update. Thanks anyway for the support and for your mega awesome project. Maybe Twitch just has something broken here
