### ISSUE TITLE
Allow Bot in multiple Discord servers

### ISSUE THREAD

**Issue by Richetoku** [PhantomBot/PhantomBot#3500]
PhantomBot Version:  v3.12.1.0
O/S Version: Ubuntu 23.04
Java Version: Java 8

Detailed Description:
I use the same bot in multiple Discord servers and this prevents the Discord module from working properly since it does not know which server to use. Would it be possible to specify something like the server ID to allow the bot to be in multiple servers and different instances of the bot can be run for each Discord server and not have an issue?

**Comment by csj90** [comment]
i tried this before and had to create a new app for 1 server
