### ISSUE TITLE
how to add gif-alerts, audio-hooks to docker-compose file

### ISSUE THREAD

**Issue by Khyretos** [PhantomBot/PhantomBot#3528]
PhantomBot Version: 3.14.0.6 (stable, Docker) (Revision: 0299705)
O/S Version: Linux
Java Version: 17.0.11+9
Web Browser Version (if Panel related):

Detailed Description:

I cannot figure out how to link the gif-alerts folder in my docker file
i tried `/media/Gifs:/opt/PhantomBot_data/config/gif-alerts`
but that does not seem to work. i just want a simple example to set either a 'environment' or 'volumes' variable to make it point to my gif folder because i cannot find these folders for the life of me.

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by gmt2001** [comment]
If you are okay with losing the current data/config of the bot, the best way is to un-comment (remove the `#`) the 5 lines in the `PhantomBot_data` section at the bottom of the [docker-compose](https://raw.githubusercontent.com/PhantomBot/PhantomBot/master/docker-compose.yml) file and change the `device: /home/someuser/phantombot` to point to a folder where it can store the entire config folder for the bot, then run `docker compose up -d` from the same folder as the docker-compose file to re-initialize. Once that is done you can do whatever you need with the sub-folders for gifs and audio

**Comment by Khyretos** [comment]
Thank you! i indeed want a specific location for the bot to be in and this works for me
