### ISSUE TITLE
GH Latest tag missing

### ISSUE THREAD

**Issue by LelieL91** [PhantomBot/PhantomBot#3560]
I just want let you know that the current latest update didn't get the "Latest" tag on it and lead my update script reinstall the same version already installed. Since this is the 2nd time that this situation happens, I want ask if this is happening randomly for no reason or if some updates are not "mandatory" so it skip the latest tag on it.
If this is a normal behavior, I'm going to just edit my script accordingly.

Thank you for your work

**Comment by gmt2001** [comment]
It is set when I publish the release on the GH website and then it just randomly gets undone while the Actions workflow is publishing the files
